'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const sb=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
type Agency={id:string;agency_name:string;agency_address:string|null;city_state_zip:string|null;contact_person:string|null;contact_email:string|null;contact_phone:string|null};
type Request={id:string;request_number:string;agency_id:string;agency_name:string;confirmed_date:string|null;status:string|null;class_status:string|null;assigned_trainer_id:string|null;basic_training:boolean;train_the_trainer:boolean;refresher_course:boolean;advanced_training:boolean};
type Att={request_id:string;person_id:string|null;email:string|null;checked_in_at:string|null;attendance_status:string|null;certificate_public_id:string|null};
type Completion={request_id:string;actual_training_date:string|null};
type Profile={id:string;full_name:string|null;email:string|null};
const date=(v:string|null)=>v?new Date(v+'T00:00:00').toLocaleDateString():'—';
const type=(r:Request)=>r.basic_training?'Basic':r.train_the_trainer?'Train the Trainer':r.refresher_course?'Refresher':r.advanced_training?'Advanced':'Training';
export default function AgencyHistory(){
 const [auth,setAuth]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[agencies,setAgencies]=useState<Agency[]>([]),[requests,setRequests]=useState<Request[]>([]),[att,setAtt]=useState<Att[]>([]),[completions,setCompletions]=useState<Completion[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[links,setLinks]=useState<any[]>([]),[selected,setSelected]=useState(''),[search,setSearch]=useState('');
 async function load(){setLoading(true);setError('');const {data:s}=await sb.auth.getSession();if(!s.session){setError('Sign in through Training Administration to view Agency Training History.');setLoading(false);return}setAuth(true);const q=await Promise.all([sb.from('agencies').select('id,agency_name,agency_address,city_state_zip,contact_person,contact_email,contact_phone').order('agency_name'),sb.from('training_requests').select('id,request_number,agency_id,agency_name,confirmed_date,status,class_status,assigned_trainer_id,basic_training,train_the_trainer,refresher_course,advanced_training').order('confirmed_date',{ascending:false}),sb.from('training_attendees').select('request_id,person_id,email,checked_in_at,attendance_status,certificate_public_id'),sb.from('training_completion_records').select('request_id,actual_training_date'),sb.from('profiles').select('id,full_name,email'),sb.from('agency_portal_links').select('agency_id,active,expires_at,submission_count')]);const bad=q.find(x=>x.error);if(bad){setError(bad.error.message);setLoading(false);return}setAgencies(q[0].data||[]);setRequests(q[1].data||[]);setAtt(q[2].data||[]);setCompletions(q[3].data||[]);setProfiles(q[4].data||[]);setLinks(q[5].data||[]);setSelected(v=>v||q[0].data?.[0]?.id||'');setLoading(false)}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>agencies.filter(a=>[a.agency_name,a.contact_person,a.contact_email].filter(Boolean).join(' ').toLowerCase().includes(search.toLowerCase().trim())),[agencies,search]);
 const agency=agencies.find(a=>a.id===selected);const rows=agency?requests.filter(r=>r.agency_id===agency.id):[];const agencyAtt=att.filter(a=>rows.some(r=>r.id===a.request_id));const trained=new Set(agencyAtt.filter(a=>a.checked_in_at||a.attendance_status==='checked_in'||a.attendance_status==='completed').map(a=>a.person_id||a.email)).size;const certificates=agencyAtt.filter(a=>a.certificate_public_id).length;const completed=rows.filter(r=>r.class_status==='Completed'||r.class_status==='Archived'||r.status==='Completed');const upcoming=rows.filter(r=>r.class_status!=='Completed'&&r.class_status!=='Archived'&&r.confirmed_date&&r.confirmed_date>=new Date().toISOString().slice(0,10)).length;const last=completed.map(r=>completions.find(c=>c.request_id===r.id)?.actual_training_date||r.confirmed_date).filter(Boolean).sort().at(-1)||null;const activeLinks=links.filter(l=>l.agency_id===agency?.id&&l.active&&(!l.expires_at||new Date(l.expires_at)>new Date())).length;
 if(loading)return <main className="shell"><section className="card"><p>Checking access…</p></section></main>;
 if(!auth)return <main className="shell"><section className="card"><h1>Agency Training History</h1><p>{error}</p><a href="/">Return to sign in</a></section></main>;
 return <main className="shell legacy-history-page"><header className="legacy-page-header"><div><h1>Agency Training History</h1><p>Agency profile, previous training, personnel trained, certificates and upcoming classes.</p></div><button onClick={()=>void load()} disabled={loading}>Refresh</button></header><div className="history-layout"><aside className="legacy-panel"><div className="history-search"><input placeholder="Search agencies…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="history-agency-list">{filtered.map(a=><button className={a.id===selected?'selected':''} key={a.id} onClick={()=>setSelected(a.id)}><strong>{a.agency_name}</strong><small>{a.contact_person||'No contact'} · {a.contact_email||'No email'}</small></button>)}{!filtered.length&&<p className="muted">No agencies found.</p>}</div></aside><section className="legacy-panel history-detail">{agency?<><div className="history-detail-body"><h2>{agency.agency_name}</h2><p className="muted">Agency training profile</p><div className="history-profile"><div><b>Address</b><span>{[agency.agency_address,agency.city_state_zip].filter(Boolean).join(', ')||'—'}</span></div><div><b>Contact</b><span>{agency.contact_person||'—'}</span></div><div><b>Email</b><span>{agency.contact_email||'—'}</span></div><div><b>Phone</b><span>{agency.contact_phone||'—'}</span></div></div><div className="history-metrics"><div><span>CLASSES</span><strong>{rows.length}</strong></div><div><span>PERSONNEL TRAINED</span><strong>{trained}</strong></div><div><span>CERTIFICATES</span><strong>{certificates}</strong></div><div><span>UPCOMING</span><strong>{upcoming}</strong></div><div><span>LAST TRAINING</span><strong>{date(last)}</strong></div></div><p className="muted">Active Agency Portal links: <b>{activeLinks}</b></p><div className="table-wrap"><table className="table"><thead><tr><th>Date</th><th>Request</th><th>Training Type</th><th>Class Status</th><th>Trainer</th><th>Attendees</th><th>Certificates</th></tr></thead><tbody>{rows.map(r=>{const a=agencyAtt.filter(x=>x.request_id===r.id);const trainer=profiles.find(p=>p.id===r.assigned_trainer_id);return <tr key={r.id}><td>{date(completions.find(c=>c.request_id===r.id)?.actual_training_date||r.confirmed_date)}</td><td>{r.request_number}</td><td>{type(r)}</td><td><span className="pill">{r.class_status||r.status||'—'}</span></td><td>{trainer?.full_name||trainer?.email||'—'}</td><td>{a.length}</td><td>{a.filter(x=>x.certificate_public_id).length}</td></tr>})}{!rows.length&&<tr><td colSpan={7}>No training history for this agency.</td></tr>}</tbody></table></div></div></>:<div className="empty-requests">Select an agency to view its training history.</div>}</section></div>{error&&<p className="error">{error}</p>}</main>;
}