'use client';
import {useEffect,useState} from 'react';

type Module={id:number;module_name:string;category:string;duration_minutes:number};
const ENDPOINT='https://wfkvcpclzhxdvknybvyb.supabase.co/functions/v1/agency-training-portal';
const resources=['Projector (No Cables)','Projector (With Cables)','TV (HDMI Cable Needed)','TV (HDMI Cable Available)','Wi-Fi','Computer with Wi-Fi','No Wi-Fi'];
const types=[['basic','Basic Backtrace Search Techniques (1 Hour 30 Minutes)'],['trainTrainer','Train the Trainer Course (8 Hours)'],['refresher','Refresher Course'],['advanced','Advanced Training']];
const empty={contact_person:'',contact_phone:'',contact_email:'',trainer_contact_name:'',trainer_contact_email:'',trainer_contact_phone:'',preferred_date:'',alternate_date:'',preferred_start_time:'',preferred_end_time:'',time_zone:'Eastern',training_format:'In Person',estimated_attendees:'',training_location:'',training_resources:[] as string[]};
export default function AgencyPortalPage(){
 const [token,setToken]=useState(''),[agency,setAgency]=useState<any>(null),[modules,setModules]=useState<Module[]>([]),[form,setForm]=useState(empty),[type,setType]=useState(''),[selected,setSelected]=useState<number[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState<any>(null);
 const call=async(body:any)=>{const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','apikey':process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||''},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw new Error(d.error||'Portal request failed.');return d};
 useEffect(()=>{const t=new URLSearchParams(window.location.search).get('token')||'';setToken(t);if(!t){setLoading(false);setError('This page must be opened using the secure agency link provided by Backtrace Training.');return}(async()=>{try{const d=await call({action:'validate',token:t});setAgency(d.agency);setModules(d.modules||[])}catch(e){setError(e instanceof Error?e.message:'Unable to open portal.')}setLoading(false)})()},[]);
 const update=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 const toggleResource=(v:string)=>setForm(x=>({...x,training_resources:x.training_resources.includes(v)?x.training_resources.filter(y=>y!==v):[...x.training_resources,v]}));
 const toolBased=type==='refresher'||type==='advanced';const total=type==='basic'?90:type==='trainTrainer'?480:selected.reduce((n,id)=>n+(modules.find(m=>m.id===id)?.duration_minutes||20),0);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const d=await call({action:'submit',token,data:{...form,estimated_attendees:form.estimated_attendees?Number(form.estimated_attendees):null,basic_training:type==='basic',train_the_trainer:type==='trainTrainer',refresher_course:type==='refresher',advanced_training:type==='advanced'},module_ids:toolBased?selected:[]});setDone(d.request)}catch(e){setError(e instanceof Error?e.message:'Unable to submit request.')}setBusy(false)}
 if(loading)return <main className="public-request-shell"><section className="public-request-card"><p>Validating your secure agency portal link…</p></section></main>;
 if(error&&!agency)return <main className="public-request-shell"><section className="public-request-card"><header><div className="library-eyebrow">BACKTRACE</div><h1>Training Request Portal</h1><p>Secure agency submission form</p></header><div className="error">{error}</div></section></main>;
 if(done)return <main className="public-request-shell"><section className="public-request-card"><header><h1>Training Request Submitted</h1><p>Your request has been received by Backtrace Training Administration.</p></header><div className="duration-banner">Request number: {done.request_number}</div><p>Please retain this number for reference. A coordinator will review the request and confirm scheduling.</p><button onClick={()=>window.print()}>Print Confirmation</button></section></main>;
 return <main className="public-request-shell"><section className="public-request-card"><header><div className="library-eyebrow">BACKTRACE</div><h1>Training Request Portal</h1><p>Secure agency submission form</p></header><div className="public-request-notice"><strong>{agency?.agency_name}</strong><br/>{[agency?.agency_address,agency?.city_state_zip].filter(Boolean).join(', ')}<br/><small>Agency identity is locked to this secure portal link.</small></div><form onSubmit={submit}>
 <fieldset><legend>Contact Information</legend><div className="form-grid"><label>Contact Person *<input required value={form.contact_person} onChange={e=>update('contact_person',e.target.value)}/></label><label>Contact Phone *<input required value={form.contact_phone} onChange={e=>update('contact_phone',e.target.value)}/></label><label>Contact Email *<input required type="email" value={form.contact_email} onChange={e=>update('contact_email',e.target.value)}/></label><label>Trainer Name *<input required value={form.trainer_contact_name} onChange={e=>update('trainer_contact_name',e.target.value)}/></label><label>Trainer Email *<input required type="email" value={form.trainer_contact_email} onChange={e=>update('trainer_contact_email',e.target.value)}/></label><label>Trainer Phone *<input required value={form.trainer_contact_phone} onChange={e=>update('trainer_contact_phone',e.target.value)}/></label></div></fieldset>
 <fieldset><legend>Scheduling Information</legend><div className="form-grid"><label>Preferred Date<input type="date" value={form.preferred_date} onChange={e=>update('preferred_date',e.target.value)}/></label><label>Alternate Date<input type="date" value={form.alternate_date} onChange={e=>update('alternate_date',e.target.value)}/></label><label>Start Time<input type="time" value={form.preferred_start_time} onChange={e=>update('preferred_start_time',e.target.value)}/></label><label>End Time<input type="time" value={form.preferred_end_time} onChange={e=>update('preferred_end_time',e.target.value)}/></label><label>Time Zone<select value={form.time_zone} onChange={e=>update('time_zone',e.target.value)}><option>Eastern</option><option>Central</option><option>Mountain</option><option>Pacific</option></select></label><label>Training Format<select value={form.training_format} onChange={e=>update('training_format',e.target.value)}><option>In Person</option><option>Virtual</option><option>Hybrid</option></select></label><label>Estimated Attendees<input type="number" min="1" value={form.estimated_attendees} onChange={e=>update('estimated_attendees',e.target.value)}/></label><label>Training Location<input value={form.training_location} onChange={e=>update('training_location',e.target.value)}/></label></div></fieldset>
 <fieldset><legend>Available Agency Resources</legend><div className="check-grid">{resources.map(v=><label className="check-label" key={v}><input type="checkbox" checked={form.training_resources.includes(v)} onChange={()=>toggleResource(v)}/><span>{v}</span></label>)}</div></fieldset>
 <fieldset><legend>Training Type Requested</legend><div className="training-type-list">{types.map(([v,label])=><label className="training-type-option" key={v}><input required type="radio" name="type" checked={type===v} onChange={()=>{setType(v);setSelected([])}}/><span><strong>{label}</strong></span></label>)}</div></fieldset>
 {toolBased&&<fieldset><legend>{type==='refresher'?'Refresher':'Advanced'} Training Tools</legend><p className="field-help">Each selected tool adds its configured training time.</p><div className="check-grid">{modules.map(m=><label className="check-label" key={m.id}><input type="checkbox" checked={selected.includes(m.id)} onChange={()=>setSelected(x=>x.includes(m.id)?x.filter(y=>y!==m.id):[...x,m.id])}/><span>{m.module_name} <small>+{m.duration_minutes||20} min</small></span></label>)}</div></fieldset>}
 <div className="duration-banner">Estimated Training Time: {total?Math.floor(total/60)+' hr '+String(total%60).padStart(2,'0')+' min':'Select training type'}</div>{error&&<p className="error">{error}</p>}<div className="form-actions"><button className="public-submit" disabled={busy}>{busy?'Submitting…':'Submit Training Request'}</button></div></form></section></main>;
}