'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
type Report={id:string;issue_number:string;summary:string;status:string;priority:string;resolution_summary:string|null;created_at:string;updated_at:string};
export default function ReportProblem(){
 const [fromRequestForm,setFromRequestForm]=useState(false),[signedIn,setSignedIn]=useState(false),[summary,setSummary]=useState(''),[details,setDetails]=useState(''),[expected,setExpected]=useState(''),[name,setName]=useState(''),[email,setEmail]=useState(''),[type,setType]=useState('Application problem'),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[reports,setReports]=useState<Report[]>([]),[reportsError,setReportsError]=useState('');
 async function loadReports(){const {data,error}=await supabase.rpc('get_my_training_bug_reports');if(error)setReportsError(error.message);else{setReports(data??[]);setReportsError('')}}
 useEffect(()=>{setFromRequestForm(new URLSearchParams(window.location.search).get('from')==='request_form');supabase.auth.getUser().then(({data})=>{if(data.user){setSignedIn(true);setEmail(data.user.email??'');void loadReports()}})},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');setMessage('');try{const {data,error}=await supabase.rpc('submit_training_bug_report',{p_data:{component:type,summary:summary.trim(),details:details.trim(),expected_behavior:expected.trim(),contact_name:name.trim(),contact_email:email.trim(),page_url:fromRequestForm?window.location.origin+'/request-training':window.location.origin+'/report-problem',user_agent:navigator.userAgent}});if(error)throw error;setMessage('Report '+data.issue_number+' submitted. Keep this reference number for follow-up.');setSummary('');setDetails('');setExpected('');if(signedIn)await loadReports()}catch(err){setError(err instanceof Error?err.message:(err as {message?:string}).message??'Unable to submit report.')}finally{setSaving(false)}}
 return <main className="shell"><section className="card report-card"><h1>Report a Problem</h1><p className="subtitle">Describe the problem. Each submission receives a tracking number.</p><form onSubmit={submit}><label>Problem type<select value={type} onChange={e=>setType(e.target.value)}><option>Application problem</option><option>Data problem</option><option>Access problem</option><option>Other</option></select></label><label>Summary<input required minLength={5} maxLength={160} value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Briefly describe the problem"/></label><label>What happened?<textarea required minLength={10} maxLength={4000} value={details} onChange={e=>setDetails(e.target.value)} placeholder="Include the steps that caused the problem and any error message." rows={7}/></label><label>What did you expect? (optional)<textarea maxLength={2000} value={expected} onChange={e=>setExpected(e.target.value)} rows={3}/></label><label>Your name (optional)<input maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label>Contact email (optional)<input type="email" maxLength={320} value={email} onChange={e=>setEmail(e.target.value)}/></label><button disabled={saving||summary.trim().length<5||details.trim().length<10}>{saving?'Submitting…':'Submit Report'}</button></form>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}<a className={fromRequestForm?'':'dashboard-return-button'} href={fromRequestForm?'/request-training':'/'}>{fromRequestForm?'Back to training request form':'Back to dashboard'}</a></section>{signedIn&&<section className="card"><h2>My Reports</h2><button onClick={loadReports}>Refresh status</button>{reportsError&&<p role="alert">{reportsError}</p>}{reports.length===0?<p>You have not submitted any reports while signed in.</p>:reports.map(report=><article key={report.id} style={{borderBottom:'1px solid #ddd',padding:'16px 0'}}><strong>{report.issue_number} — {report.summary}</strong><p>{report.status} · {report.priority} priority · Updated {new Date(report.updated_at).toLocaleString()}</p>{report.resolution_summary&&<p>Resolution: {report.resolution_summary}</p>}</article>)}</section>}</main>
}

