'use client';

import {useMemo,useState} from 'react';

type GuideSection={
  title:string;
  audience:string;
  summary:string;
  steps:string[];
  link:string;
  linkLabel:string;
  note?:string;
};

const sections:GuideSection[]=[
 {title:'Dashboard',audience:'All active users',summary:'Use the dashboard as the operational starting point for open requests, upcoming training, agencies, and quick actions.',steps:['Review Open Requests, Received, Upcoming 30 Days, Unassigned, and Active Agencies.','Use Upcoming Training to see confirmed classes in the next 30 days.','Use Quick Actions to open Today, Requests, Attendance, Attendees, Agency History, or Completion.','Administrators also see read-only System Status, release lineage, and Bug Report summaries.'],link:'/',linkLabel:'Open Dashboard'},
 {title:'Training Requests',audience:'All active users; edits depend on role',summary:'Review agency requests, open a specific request, and share the public agency request form.',steps:['Open Training > Requests.','Search or filter the request list.','Use Agency Request Link & QR to copy the public form URL, open the form, or save its QR code.','Select Open on a request to go directly to that request record.','Use Download CSV to export the currently filtered request list.'],link:'/requests',linkLabel:'Open Requests'},
 {title:'Edit, Assign & Schedule a Request',audience:'Administrator / Coordinator / assigned Trainer',summary:'Maintain request details, assign a trainer, confirm the schedule, and add a Teams meeting link for virtual/hybrid training.',steps:['Open the request from Training Requests or a deep link.','Administrators can edit the full agency, contact, training-type, resource, module, and internal-note record.','Administrators and Coordinators choose the assigned trainer, confirmed date, and confirmed start time.','Select Confirm Schedule. The server checks trainer conflicts before saving.','For Virtual or Hybrid training, Administrators and Coordinators can save an approved Microsoft Teams meeting link.','Trainers can edit only unlocked requests they created or that are assigned to them.'],link:'/requests/edit',linkLabel:'Open Request Editor',note:'Completed, Closed, Archived, Cancelled, and Finalized records remain locked.'},
 {title:'Training Calendar',audience:'All active users; scheduling is manager-only',summary:'Use month, week, or day views to manage the confirmed schedule, unassigned work, conflicts, and trainer workload.',steps:['Open Training > Calendar.','Switch between Month, Week, and Day.','Filter by trainer, status, or search text.','Select a scheduled event or an unassigned request to review details.','Administrators and Coordinators can set the trainer/date/time and select Save Schedule.','Resolve any overlap shown by the conflict check before saving.'],link:'/calendar',linkLabel:'Open Calendar'},
 {title:'Today',audience:'All active users',summary:'Run the day-of-training workflow from one screen.',steps:['Open Training > Today.','Trainers see only classes assigned to them; other permitted roles see the scheduled day view.','Use Start Class when the class is ready to begin.','Open Attendance, the Request record, or Join Teams directly from the class card.','Use Close Class when training is finished; the workflow can hand off to Completion.'],link:'/today',linkLabel:'Open Today'},
 {title:'Classes & Attendance',audience:'All active users with workflow permissions',summary:'Generate a secure class link, manage the roster, print sign-in/trainer information, issue certificates, and search past classes.',steps:['Open Training > Classes and Attendance.','Select an active class. Past/closed classes are not kept in the active-class selector.','Use Generate Class to create or rotate the secure attendance link.','Copy Link, Open Public Page, or Download QR to share the self-service sign-up/check-in page.','Use Add Attendee for manual roster entry when needed.','Use Print Sign-In Sheet or Trainer Information PDF for class documents.','Issue an individual certificate or Issue Certificates to Checked-In for all eligible checked-in attendees.','Use Past Training Classes to search historical classes, reopen details, export results, print the class sign-in information, and view stored certificates.'],link:'/classes',linkLabel:'Open Classes & Attendance',note:'The removed paper-sign-in import workflow is intentionally not part of the current application.'},
 {title:'Completions & Certificates',audience:'Authorized training staff',summary:'Finalize completed training records and review the certificates tied to a completion.',steps:['Open Training > Completions and Certificates.','Select the applicable class/completion record.','Review attendance and completion details before finalization.','Use the completion workflow to save/finalize the record as permitted.','Use View in the Certificates column to list issued certificates for that completion.','Open a certificate using its protected UUID record.'],link:'/completions',linkLabel:'Open Completions'},
 {title:'Attendee Directory',audience:'All active users',summary:'Search people rather than raw roster rows and review their full class/certificate history.',steps:['Open People > Attendees.','Search by name, email, Badge # / ID #, or agency.','Select a person to open their profile history.','Review classes, certificates, first seen, and last training metrics.','Open a stored certificate from the class-history table.','Use Download CSV for the filtered directory.'],link:'/attendees',linkLabel:'Open Attendees'},
 {title:'Agency Directory',audience:'Administrator / Coordinator',summary:'Create, edit, activate, or deactivate agencies used by Requests and Agency Portal.',steps:['Open People > Agencies.','Search or filter Active/Inactive agencies.','Use New Agency to create an agency profile.','Use Edit to maintain agency and contact information.','Use Activate/Deactivate to control whether an agency is operational for manager workflows.','Export the filtered agency list to CSV when needed.'],link:'/agencies',linkLabel:'Open Agencies'},
 {title:'Agency Training History',audience:'All active users',summary:'Review each agency’s training history, personnel trained, certificates, upcoming classes, and portal activity.',steps:['Open People > Agency History.','Search for and select an agency.','Review agency profile/contact information and summary metrics.','Review each historical class, trainer, attendance count, and certificate count.','Use Attendee Directory, Past Classes, or Completions when an individual certificate needs to be opened.'],link:'/agency-history',linkLabel:'Open Agency History'},
 {title:'Agency Portal',audience:'Administrator / Coordinator',summary:'Create and revoke secure agency-specific Training Request links.',steps:['Open People > Agency Portal.','Select Create Agency Portal Link.','Choose an active agency and enter a label.','Optionally set an expiration date/time and maximum submissions; leave maximum blank for Unlimited.','Create the link and copy the full URL immediately—the secure token is only returned at creation time.','Use Open Portal to test the generated link.','Use Revoke to close an active link when necessary.'],link:'/agency-portal/manage',linkLabel:'Open Agency Portal'},
 {title:'Management Reports',audience:'Administrator / Coordinator',summary:'Use the management analytics dashboard for demand, completion, workload, agency activity, tools, and request detail.',steps:['Open Training > Reports.','Choose This Year, Last 90 Days, Last 30 Days, All Time, or a custom date range.','Review completion rate, training hours, attendees, lead time, and Needs Action.','Review monthly volume, trainer workload, agency activity, requested tools, and request detail.','Use Print Report or Export CSV for the current date range.'],link:'/reports',linkLabel:'Open Reports'},
 {title:'Notifications',audience:'All active users',summary:'Review in-app notifications, generate reminders, and maintain read/unread state.',steps:['Open Notifications.','Use Check Reminders to generate deduplicated in-app reminders.','Filter by Unread/Read, notification type, or search text.','Use Open when a notification contains a valid Backtrace action.','Use Mark Read, Mark Unread, or Mark All Read as needed.','The navigation badge updates when unread state changes.'],link:'/notifications',linkLabel:'Open Notifications'},
 {title:'Resource Library',audience:'All active users; management is Administrator-only',summary:'Browse training resources by type/state, view current files, and review version history.',steps:['Open Help > Resource Library.','Search or filter resources by state and resource type.','Use View to open the current stored file.','Use Versions to review version history.','Administrators can Add Resource, create a New Version, and Archive a resource.','National / General should be used only for resources that apply everywhere.'],link:'/library',linkLabel:'Open Resource Library'},
 {title:'User Management',audience:'Administrator',summary:'Create and administer Training Administration user accounts.',steps:['Open Administration > Users.','Create a Trainer, Coordinator, or Administrator and provide the generated temporary password directly to the user.','Edit the user name, role, and active status as needed.','Existing users can also be assigned Viewer.','Use Reset Password only when a new temporary password is required.','Review the Administration Activity list for recent account-management actions.'],link:'/user-management',linkLabel:'Open User Management'},
 {title:'Activity & Audit History',audience:'Administrator',summary:'Review exact Backtrace Training audit history across requests, users, agencies, attendance, authentication, and administration.',steps:['Open Administration > Activity.','Use the 7 / 30 / 90 Days or All presets, or set a custom range.','Filter by user/system actor, category, or search text.','Use View Details to inspect changed fields and previous/new values.','Export the filtered audit history to CSV.'],link:'/activity',linkLabel:'Open Activity History'},
 {title:'Bug Reports',audience:'Administrator; submission is public/authenticated',summary:'Review problems submitted from the public request form and the authenticated tracker.',steps:['Users can select Report a Problem from the tracker or public Training Request form.','Administrators open Administration > Bug Reports.','Search/filter reports and review the submitted page, component, details, and source.','Move reports through Open, In Review, Resolved, or Closed and save administrator notes.'],link:'/bug-reports',linkLabel:'Open Bug Reports'},
 {title:'System Status & Communications Safety',audience:'Administrator',summary:'Review production safeguards without enabling protected features.',steps:['Open Administration > System Status.','Confirm Training Administration version and the GitHub + Vercel + Supabase architecture.','Confirm Release Writes remain OFF.','Confirm Email Delivery, Webhooks, Tracking, and Email Delivery Cron remain OFF.','Confirm the protected email-queue DELETE/TRUNCATE guard is ON.','Review the live email queue count before any future communications activation.','Run read-only connectivity checks when needed.'],link:'/health',linkLabel:'Open System Status',note:'The demo email queue was intentionally cleared. Keep email delivery disabled until a future communications release is explicitly authorized and validated.'}
];

const roles=[
 ['Administrator','Full administration, user management, agencies/portal, request editing, scheduling, reports, audits, system status, and resource management.'],
 ['Coordinator','Manager scheduling and agency/portal workflows, reports, and operational training management without Administrator-only system/user controls.'],
 ['Trainer','Works with unlocked requests created by or assigned to the trainer and runs assigned day-of-training workflows.'],
 ['Viewer','Read-only access where permitted by application/database policy.']
];

export default function HelpPage(){
 const [search,setSearch]=useState('');
 const filtered=useMemo(()=>{const term=search.trim().toLowerCase();return sections.filter(section=>!term||[section.title,section.audience,section.summary,...section.steps,section.note||''].join(' ').toLowerCase().includes(term));},[search]);
 return <main className="shell app-guide-page">
  <header className="legacy-page-header app-guide-header"><div><span className="library-eyebrow">BACKTRACE TRAINING ADMINISTRATION</span><h1>App User Guide</h1><p>Current operational guide for Training Administration v2.1.10.</p></div><div className="app-guide-actions"><button onClick={()=>window.print()}>Print Guide</button><a href="/">Back to Dashboard</a></div></header>

  <section className="app-guide-intro"><div><strong>Core workflow</strong><p>Request → assign/schedule → generate class → attendance/check-in → close/finalize → certificates/history.</p></div><div><strong>Protected production state</strong><p>Release writes and outbound communications remain protected. Use System Status for the live safety state.</p></div></section>

  <section className="legacy-panel"><div className="panel-heading"><div><h2>Role Guide</h2><span>What each application role is intended to do</span></div></div><div className="app-guide-role-grid">{roles.map(([role,description])=><article key={role}><strong>{role}</strong><p>{description}</p></article>)}</div></section>

  <section className="legacy-panel app-guide-search-panel"><label>SEARCH THIS GUIDE<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Try: certificate, schedule, agency portal, report, notification..."/></label><button onClick={()=>setSearch('')}>Clear</button></section>

  <section className="app-guide-sections">{filtered.map((section,index)=><article className="app-guide-section" key={section.title}><header><div><span>SECTION {String(index+1).padStart(2,'0')} · {section.audience}</span><h2>{section.title}</h2><p>{section.summary}</p></div><a href={section.link}>{section.linkLabel}</a></header><ol>{section.steps.map(step=><li key={step}>{step}</li>)}</ol>{section.note&&<div className="app-guide-note"><strong>Important</strong><span>{section.note}</span></div>}</article>)}</section>

  {!filtered.length&&<section className="legacy-panel"><p>No guide sections match that search. Clear the search and try again.</p></section>}

  <section className="legacy-panel app-guide-troubleshooting"><h2>Troubleshooting</h2><div><article><strong>A button is unavailable</strong><p>Check the record status and your role. Completed/Archived records and manager-only operations are intentionally locked.</p></article><article><strong>A class is missing from the active selector</strong><p>Past or closed classes belong under Past Training Classes, where history, sign-in information, and certificates remain available.</p></article><article><strong>A schedule will not save</strong><p>Confirm trainer/date/time are set and resolve any trainer overlap shown by the conflict checker.</p></article><article><strong>A certificate is not visible</strong><p>Confirm the attendee was checked in and certificate issuance completed. Use Past Classes, Attendee Directory, or Completions to reopen an existing certificate.</p></article><article><strong>Something is not working</strong><p>Use <a href="/report-problem">Report a Problem</a> and include the page, component, what happened, and the expected result.</p></article></div></section>
 </main>;
}
