'use client';

import {useEffect,useMemo,useState} from 'react';
import {createClient,Session} from '@supabase/supabase-js';

type Agency={id:string;agency_name:string;active:boolean;contact_person:string|null;contact_email:string|null;};
type PortalLink={id:string;agency_id:string;token_hint:string;label:string;active:boolean;expires_at:string|null;max_submissions:number|null;submission_count:number;last_used_at:string|null;};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
const blank={agency_id:'',label:'Agency Training Request Portal',expires:'',max:''};

export default function AgencyPortal(){
 const [session,setSession]=useState<Session|null>(null);const [role,setRole]=useState('');const [agencies,setAgencies]=useState<Agency[]>([]);const [links,setLinks]=useState<PortalLink[]>([]);
 const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [saving,setSaving]=useState(false);
 const [showCreate,setShowCreate]=useState(false);const [form,setForm]=useState(blank);const [result,setResult]=useState<{url:string;token:string;agency_name:string;expires_at:string|null;max_submissions:number|null}|null>(null);

 async function load(){setLoading(true);setError('');const {data:auth}=await supabase.auth.getSession();setSession(auth.session);if(!auth.session){setError('Manager sign-in is required.');setLoading(false);return;}const [{data:profile,error:profileError},{data:agencyData,error:agencyError},{data:linkData,error:linkError}]=await Promise.all([supabase.from('profiles').select('role,active').eq('id',auth.session.user.id).maybeSingle(),supabase.from('agencies').select('id,agency_name,active,contact_person,contact_email').order('agency_name'),supabase.from('agency_portal_links').select('id,agency_id,token_hint,label,active,expires_at,max_submissions,submission_count,last_used_at').order('created_at',{ascending:false})]);if(profileError||!profile?.active||!['admin','coordinator'].includes(profile.role)){setRole(profile?.role||'');setError(profileError?.message||'Administrator or Coordinator access is required.');setLoading(false);return;}setRole(profile.role);setAgencies(agencyData??[]);setLinks(linkData??[]);setError(agencyError?.message||linkError?.message||'');setLoading(false);}
 useEffect(()=>{void load();},[]);
 function closed(link:PortalLink){return!link.active||Boolean(link.expires_at&&new Date(link.expires_at)<=new Date())||(link.max_submissions!=null&&link.submission_count>=link.max_submissions);}
 function name(id:string){return agencies.find(a=>a.id===id)?.agency_name||'Unknown Agency';}
 const visible=useMemo(()=>{const term=search.toLowerCase().trim();return links.filter(link=>{const isClosed=closed(link);const statusMatch=!status||(status==='active'?!isClosed:isClosed);const text=[name(link.agency_id),link.label,link.token_hint].join(' ').toLowerCase();return statusMatch&&(!term||text.includes(term));});},[links,agencies,search,status]);
 async function createLink(){if(!form.agency_id){setError('Select an agency.');return;}setSaving(true);setError('');setResult(null);const expires=form.expires?new Date(form.expires).toISOString():null;const max=form.max?Number(form.max):null;const {data,error}=await supabase.rpc('create_agency_portal_link',{p_agency_id:form.agency_id,p_label:form.label.trim()||null,p_expires_at:expires,p_max_submissions:max});if(error)setError(error.message);else{setResult({url:data.url,token:data.token,agency_name:data.agency_name,expires_at:data.expires_at,max_submissions:data.max_submissions});await load();}setSaving(false);}
 async function revoke(id:string){if(!window.confirm('Revoke this portal link? Agencies will no longer be able to submit through it.'))return;const {error}=await supabase.rpc('revoke_agency_portal_link',{p_link_id:id});if(error)setError(error.message);else await load();}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);}catch{setError('Unable to copy the link.');}}
 function openCreate(){setForm(blank);setResult(null);setError('');setShowCreate(true);}
 if(loading&&!session)return <main className="shell"><section className="card"><h1>Agency Portal</h1><p>{error||'Loading agency portal…'}</p></section></main>;
 if(!session||!['admin','coordinator'].includes(role))return <main className="shell"><section className="card"><h1>Agency Portal</h1><p>{error||'Manager permission is required.'}</p><a href="/">Back to dashboard</a></section></main>;
 const active=links.filter(link=>!closed(link)).length,closedCount=links.filter(closed).length;
 return <main className="shell legacy-admin-page"><header className="legacy-page-header"><div><h1>Agency Portal</h1><p>Create and manage secure agency-specific Training Request links.</p></div><button className="primary-button" onClick={openCreate}>Create Agency Portal Link</button></header>
 <section className="settings-status-grid"><div><span>ACTIVE AGENCIES</span><strong>{agencies.filter(a=>a.active).length}</strong></div><div><span>ACTIVE LINKS</span><strong>{active}</strong></div><div><span>SUBMISSIONS</span><strong>{links.reduce((sum,l)=>sum+l.submission_count,0)}</strong></div><div><span>CLOSED LINKS</span><strong>{closedCount}</strong></div></section>
 <section className="legacy-panel"><div className="panel-heading"><div><h2>Agency Portal Links</h2><span>{visible.length} links</span></div><button onClick={()=>void load()} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button></div><div className="portal-toolbar"><input placeholder="Search agency, label or token hint" value={search} onChange={e=>setSearch(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All links</option><option value="active">Active</option><option value="closed">Expired / Revoked / Used Up</option></select><button onClick={()=>{setSearch('');setStatus('')}}>Clear</button></div>{error&&!showCreate&&<p className="error">{error}</p>}<div className="table-wrap"><table className="table portal-link-table"><thead><tr><th>Agency</th><th>Label</th><th>Status</th><th>Token</th><th>Usage</th><th>Expires</th><th>Last Used</th><th></th></tr></thead><tbody>{visible.map(link=><tr key={link.id}><td><strong>{name(link.agency_id)}</strong></td><td>{link.label}</td><td><span className="pill">{!link.active?'Revoked':closed(link)?'Closed':'Active'}</span></td><td>{link.token_hint}…</td><td>{link.submission_count}{link.max_submissions==null?' / Unlimited':' / '+link.max_submissions}</td><td>{link.expires_at?new Date(link.expires_at).toLocaleString():'—'}</td><td>{link.last_used_at?new Date(link.last_used_at).toLocaleString():'—'}</td><td>{link.active&&!closed(link)&&<button className="link-revoke" onClick={()=>void revoke(link.id)}>Revoke</button>}</td></tr>)}</tbody></table></div>{!visible.length&&<p className="empty-requests">No agency portal links found.</p>}</section>
 {showCreate&&<div className="upload-modal-backdrop"><section className="upload-modal portal-create-modal" role="dialog" aria-modal="true"><header><div><h2>Create Agency Portal Link</h2><p>Create a secure agency-specific Training Request URL.</p></div><button className="modal-close" onClick={()=>setShowCreate(false)}>Close</button></header><div className="upload-body"><div className="portal-create-grid"><label className="span-two">Agency<select required value={form.agency_id} onChange={e=>setForm({...form,agency_id:e.target.value})}><option value="">Select agency</option>{agencies.filter(a=>a.active).map(a=><option key={a.id} value={a.id}>{a.agency_name}</option>)}</select></label><label className="span-two">Link Label<input value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/></label><label>Expiration Date / Time<input type="datetime-local" value={form.expires} onChange={e=>setForm({...form,expires:e.target.value})}/></label><label>Maximum Submissions<input type="number" min="1" placeholder="Unlimited" value={form.max} onChange={e=>setForm({...form,max:e.target.value})}/></label></div>{error&&<p className="error">{error}</p>}{result&&<div className="portal-created-result"><strong>Portal link created for {result.agency_name}.</strong><p>Copy this URL now. The full secure token cannot be reconstructed later.</p><input readOnly value={result.url}/><div className="credential-actions"><button onClick={()=>void copy(result.url)}>Copy Link</button><button onClick={()=>window.open(result.url,'_blank','noopener,noreferrer')}>Open Portal</button></div></div>}</div><footer><button className="cancel-upload" onClick={()=>setShowCreate(false)}>{result?'Close':'Cancel'}</button>{!result&&<button disabled={saving} onClick={()=>void createLink()}>{saving?'Creating…':'Create Link'}</button>}</footer></section></div>}
 </main>;
}
