'use client';

import {useEffect,useMemo,useState} from 'react';
import {createClient,Session} from '@supabase/supabase-js';

type Agency={id:string;agency_name:string;active:boolean;contact_person:string|null;contact_email:string|null;};
type PortalLink={id:string;agency_id:string;token_hint:string;label:string;active:boolean;expires_at:string|null;max_submissions:number|null;submission_count:number;last_used_at:string|null;};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);

export default function AgencyPortal(){const [session,setSession]=useState<Session|null>(null);const [role,setRole]=useState('');const [agencies,setAgencies]=useState<Agency[]>([]);const [links,setLinks]=useState<PortalLink[]>([]);const [search,setSearch]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 async function load(){setLoading(true);setError('');const {data:auth}=await supabase.auth.getSession();setSession(auth.session);if(!auth.session){setError('Manager sign-in is required.');setLoading(false);return;}const [{data:profile},{data:agencyData,error:agencyError},{data:linkData,error:linkError}]=await Promise.all([supabase.from('profiles').select('role').eq('id',auth.session.user.id).maybeSingle(),supabase.from('agencies').select('id,agency_name,active,contact_person,contact_email').order('agency_name'),supabase.from('agency_portal_links').select('id,agency_id,token_hint,label,active,expires_at,max_submissions,submission_count,last_used_at').order('created_at',{ascending:false})]);setRole(profile?.role||'');setAgencies(agencyData??[]);setLinks(linkData??[]);setError(agencyError?.message||linkError?.message||'');setLoading(false);}
 useEffect(()=>{void load();},[]);
 const rows=useMemo(()=>agencies.filter(a=>{const term=search.toLowerCase().trim();return !term||[a.agency_name,a.contact_person,a.contact_email].filter(Boolean).join(' ').toLowerCase().includes(term);}).map(a=>({agency:a,links:links.filter(l=>l.agency_id===a.id)})),[agencies,links,search]);
 if(!session||loading)return <main className="shell"><section className="card"><h1>Agency Portal</h1><p>{error||'Loading agency portal…'}</p></section></main>;
 if(!['admin','coordinator'].includes(role))return <main className="shell"><section className="card"><h1>Agency Portal</h1><p>Manager permission is required.</p><a href="/">Back to dashboard</a></section></main>;
 return <main className="shell legacy-admin-page"><header className="legacy-page-header"><div><h1>Agency Portal</h1><p>Create and manage secure agency-specific request links.</p></div><div className="portal-header-actions"><button onClick={()=>void load()} disabled={loading}>Refresh</button><a href="/agencies">Back to agencies</a></div></header><section className="settings-status-grid"><div><span>ACTIVE AGENCIES</span><strong>{agencies.filter(a=>a.active).length}</strong><small>Available for portal access</small></div><div><span>ACTIVE LINKS</span><strong>{links.filter(l=>l.active).length}</strong><small>Secure agency links</small></div><div><span>SUBMISSIONS</span><strong>{links.reduce((sum,l)=>sum+l.submission_count,0)}</strong><small>Total portal submissions</small></div><div><span>EXPIRED LINKS</span><strong>{links.filter(l=>l.expires_at&&new Date(l.expires_at)<new Date()).length}</strong><small>Requires review</small></div></section><section className="legacy-panel"><div className="panel-heading"><h2>Agency Portal Links</h2><span>{rows.length} agencies</span></div><div className="portal-toolbar"><input placeholder="Search agency or contact" value={search} onChange={event=>setSearch(event.target.value)}/><button disabled>Create Portal Link</button></div>{error&&<p className="error">{error}</p>}<div className="portal-list">{rows.map(({agency,links:agencyLinks})=><article key={agency.id}><div><strong>{agency.agency_name}</strong><small>{agency.contact_person||'No contact'}{agency.contact_email?' · '+agency.contact_email:''}</small></div><div className="portal-link-list">{agencyLinks.length?agencyLinks.map(link=><div key={link.id}><strong>{link.label}</strong><span className={link.active?'portal-active':'portal-inactive'}>{link.active?'Active':'Inactive'}</span><small>Used {link.submission_count} times · {link.expires_at?'Expires '+new Date(link.expires_at).toLocaleDateString():'No expiration'}</small></div>):<span className="muted">No portal links created</span>}</div></article>)}</div>{!rows.length&&<p className="empty-requests">No agencies match the search.</p>}</section></main>;
}