'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
type Bug={id:string;issue_number:string;source:string;component:string;summary:string;details:string;expected_behavior:string|null;contact_name:string|null;contact_email:string|null;page_url:string|null;app_version:string|null;status:string;priority:string;assigned_to:string|null;admin_notes:string|null;resolution_summary:string|null;created_at:string;updated_at:string};
type Owner={id:string;full_name:string|null;email:string|null};
type History={id:string;actor_id:string|null;action:string;changes:Record<string,{before?:unknown;after?:unknown}>;created_at:string};
const statuses=['Open','In Review','Resolved','Closed'],priorities=['Low','Normal','High','Critical'];
export default function BugReports(){
 const [rows,setRows]=useState<Bug[]>([]),[owners,setOwners]=useState<Owner[]>([]),[filter,setFilter]=useState('All statuses'),[priority,setPriority]=useState('All priorities'),[owner,setOwner]=useState('All owners'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<string|null>(null);
 async function load(){setError('');try{const {data:auth,error:authError}=await supabase.auth.getUser();if(authError||!auth.user)throw new Error('Administrator sign-in is required.');const {data:me,error:profileError}=await supabase.from('profiles').select('role,active').eq('id',auth.user.id).maybeSingle();if(profileError)throw profileError;if(me?.role!=='admin'||!me.active)throw new Error('Administrator access is required.');const [reports,people]=await Promise.all([supabase.from('training_bug_reports').select('*').order('created_at',{ascending:false}),supabase.from('profiles').select('id,full_name,email').eq('active',true).in('role',['admin','coordinator']).order('full_name')]);if(reports.error)throw reports.error;if(people.error)throw people.error;setRows(reports.data??[]);setOwners(people.data??[])}catch(err){setError((err as {message?:string}).message??'Unable to load reports.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>{const term=search.trim().toLowerCase();return rows.filter(row=>(filter==='All statuses'||row.status===filter)&&(priority==='All priorities'||row.priority===priority)&&(owner==='All owners'||(owner==='Unassigned'?!row.assigned_to:row.assigned_to===owner))&&(!term||[row.issue_number,row.component,row.summary,row.details,row.contact_name,row.contact_email].join(' ').toLowerCase().includes(term)))},[rows,filter,priority,owner,search]);
 const current=rows.find(row=>row.id===selected);
 if(loading)return <main className="shell"><section className="card"><h1>Bug Reports</h1><p>Loading tracker…</p></section></main>;
 return <main className="shell"><section className="card"><div className="header"><div><h1>Bug Reports</h1><p>Track submitted problems through resolution.</p></div><a href="/">Back to dashboard</a></div>{error&&<p role="alert">{error}</p>}<p>{rows.filter(r=>r.status==='Open').length} open · {rows.filter(r=>r.status==='In Review').length} in review · {rows.filter(r=>!r.assigned_to&&['Open','In Review'].includes(r.status)).length} unassigned · {rows.filter(r=>r.priority==='Critical'&&['Open','In Review'].includes(r.status)).length} critical</p><div className="controls"><input aria-label="Search bug reports" placeholder="Search ticket, summary, or contact" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter status" value={filter} onChange={e=>setFilter(e.target.value)}><option>All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><select aria-label="Filter priority" value={priority} onChange={e=>setPriority(e.target.value)}><option>All priorities</option>{priorities.map(s=><option key={s}>{s}</option>)}</select><select aria-label="Filter owner" value={owner} onChange={e=>setOwner(e.target.value)}><option>All owners</option><option>Unassigned</option>{owners.map(p=><option key={p.id} value={p.id}>{p.full_name||p.email||p.id}</option>)}</select><button onClick={load}>Refresh</button><a href="/report-problem">Submit a problem</a></div>{filtered.length===0?<p>No bug reports match the current filters.</p>:<div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Ticket</th><th>Summary</th><th>Status</th><th>Priority</th><th>Owner</th><th>Updated</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td><button onClick={()=>setSelected(row.id)}>{row.issue_number}</button></td><td>{row.summary}</td><td>{row.status}</td><td>{row.priority}</td><td>{owners.find(p=>p.id===row.assigned_to)?.full_name||owners.find(p=>p.id===row.assigned_to)?.email||(row.assigned_to?'Inactive owner':'Unassigned')}</td><td>{new Date(row.updated_at).toLocaleString()}</td></tr>)}</tbody></table></div>}</section>{current&&<Ticket key={current.id+current.updated_at} row={current} owners={owners} onSaved={load} onClose={()=>setSelected(null)}/>}</main>
}
function Ticket({row,owners,onSaved,onClose}:{row:Bug;owners:Owner[];onSaved:()=>Promise<void>;onClose:()=>void}){
 const [status,setStatus]=useState(row.status),[priority,setPriority]=useState(row.priority),[owner,setOwner]=useState(row.assigned_to??''),[notes,setNotes]=useState(row.admin_notes??''),[resolution,setResolution]=useState(row.resolution_summary??''),[saving,setSaving]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState<History[]>([]),[historyError,setHistoryError]=useState('');
 useEffect(()=>{let active=true;supabase.from('training_bug_report_history').select('id,actor_id,action,changes,created_at').eq('bug_report_id',row.id).order('created_at',{ascending:false}).then(({data,error})=>{if(active){setHistory(data??[]);setHistoryError(error?.message??'')}});return()=>{active=false}},[row.id,row.updated_at]);
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const {error}=await supabase.rpc('update_training_bug_report',{p_id:row.id,p_status:status,p_priority:priority,p_assigned_to:owner||null,p_admin_notes:notes,p_resolution_summary:resolution,p_expected_updated_at:row.updated_at});if(error)throw error;await onSaved()}catch(err){setError((err as {message?:string}).message??'Unable to save ticket.')}finally{setSaving(false)}}
 function display(field:string,value:unknown){if(value===null||value===undefined||value==='')return 'None';if(field==='assigned_to')return owners.find(p=>p.id===value)?.full_name||owners.find(p=>p.id===value)?.email||String(value);return String(value)}
 return <section className="card"><button onClick={onClose}>Close details</button><h2>{row.issue_number} — {row.summary}</h2><p>{row.component} · Submitted {new Date(row.created_at).toLocaleString()} · {row.source} · Version {row.app_version||'Unknown'}</p><h3>Problem</h3><p style={{whiteSpace:'pre-wrap'}}>{row.details}</p>{row.expected_behavior&&<><h3>Expected behavior</h3><p style={{whiteSpace:'pre-wrap'}}>{row.expected_behavior}</p></>}{(row.contact_name||row.contact_email)&&<p>Contact: {row.contact_name} {row.contact_email}</p>}{row.page_url&&/^https:\/\//i.test(row.page_url)&&<a href={row.page_url} target="_blank" rel="noreferrer">Reported page</a>}<form onSubmit={save}><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}>{priorities.map(s=><option key={s}>{s}</option>)}</select></label><label>Assigned owner<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Unassigned</option>{row.assigned_to&&!owners.some(p=>p.id===row.assigned_to)&&<option value={row.assigned_to}>Inactive owner — choose a new owner</option>}{owners.map(p=><option key={p.id} value={p.id}>{p.full_name||p.email||p.id}</option>)}</select></label><label>Internal administrator notes<textarea maxLength={4000} rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></label><label>Resolution summary (visible to the submitter)<textarea required={status==='Resolved'||status==='Closed'} maxLength={2000} rows={4} value={resolution} onChange={e=>setResolution(e.target.value)}/></label><button disabled={saving}>{saving?'Saving…':'Save ticket'}</button></form>{error&&<p role="alert">{error}</p>}<h3>Change history</h3>{historyError&&<p role="alert">{historyError}</p>}{history.map(event=><article key={event.id} style={{borderTop:'1px solid #ddd',padding:'12px 0'}}><strong>{event.action}</strong> · {new Date(event.created_at).toLocaleString()}<p>By {owners.find(p=>p.id===event.actor_id)?.full_name||owners.find(p=>p.id===event.actor_id)?.email||(event.actor_id?'Signed-in user':'Public submitter')}</p>{Object.entries(event.changes).map(([field,change])=><p key={field} style={{whiteSpace:'pre-wrap'}}>{field.replace(/_/g,' ')}: {display(field,change.before)} → {display(field,change.after)}</p>)}</article>)}</section>
}
