'use client';

import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

type Notification={id:number;notification_type:string|null;title:string|null;message:string|null;severity:string|null;action_url:string|null;read_at:string|null;created_at:string|null;};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);

export default function NotificationsPage(){
  const [rows,setRows]=useState<Notification[]>([]);const [search,setSearch]=useState('');const [view,setView]=useState('All notifications');const [error,setError]=useState('');const [loading,setLoading]=useState(true);
  async function load(){setLoading(true);setError('');const {data,error}=await supabase.from('training_notifications').select('id,notification_type,title,message,severity,action_url,read_at,created_at').order('created_at',{ascending:false});if(error)setError(error.message);else setRows(data??[]);setLoading(false);}useEffect(()=>{void load();const refresh=()=>void load();const timer=window.setInterval(refresh,30000);window.addEventListener('focus',refresh);const visible=()=>{if(document.visibilityState==='visible')refresh()};document.addEventListener('visibilitychange',visible);return()=>{window.clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',visible)}},[]);async function markRead(row:Notification){if(row.read_at)return;const {error}=await supabase.from('training_notifications').update({read_at:new Date().toISOString()}).eq('id',row.id);if(error)setError(error.message);else await load();}async function markAllRead(){const ids=rows.filter(row=>!row.read_at).map(row=>row.id);if(!ids.length)return;const {error}=await supabase.from('training_notifications').update({read_at:new Date().toISOString()}).in('id',ids);if(error)setError(error.message);else await load();}function openAction(row:Notification){if(!row.action_url)return;try{const url=new URL(row.action_url,window.location.origin);if(url.origin===window.location.origin)window.location.assign(url.pathname+url.search+url.hash);else setError('This notification action points outside Training Administration and was not opened.');}catch{setError('This notification action is invalid.');}}
  const filtered=useMemo(()=>{const term=search.trim().toLowerCase();return rows.filter(row=>{const viewMatch=view==='All notifications'||(view==='Unread'&&!row.read_at)||(view==='Read'&&Boolean(row.read_at));const text=[row.title,row.message,row.notification_type,row.severity].filter(Boolean).join(' ').toLowerCase();return viewMatch&&(!term||text.includes(term));});},[rows,search,view]);
  function downloadCsv(){const header=['Title','Type','Severity','Message','Created','Status'];const lines=filtered.map(row=>[row.title,row.notification_type,row.severity,row.message,row.created_at,row.read_at?'Read':'Unread'].map(value=>'"'+String(value??'').replaceAll('"','""')+'"').join(','));const blob=new Blob([[header.join(','),...lines].join('\\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='backtrace-notifications.csv';link.click();URL.revokeObjectURL(url);}
  return <main className="shell"><header className="header"><div><div className="brand">Notifications</div><div className="subtitle">Your notification history and unread items</div></div><a href="/">Back to dashboard</a></header><section className="grid"><div className="metric">Notifications<strong>{rows.length}</strong></div><div className="metric">Unread<strong>{rows.filter(row=>!row.read_at).length}</strong></div><div className="metric">Showing<strong>{filtered.length}</strong></div></section><section className="card"><div className="controls"><input aria-label="Search notifications" placeholder="Search title, message, type, or severity" value={search} onChange={event=>setSearch(event.target.value)}/><select aria-label="Filter notifications" value={view} onChange={event=>setView(event.target.value)}><option>All notifications</option><option>Unread</option><option>Read</option></select><button disabled={loading} onClick={load}>{loading?'Loading…':'Refresh notifications'}</button><button disabled={!rows.some(row=>!row.read_at)} onClick={()=>void markAllRead()}>Mark All Read</button><button disabled={!filtered.length} onClick={downloadCsv}>Download CSV</button></div>{error&&<p>{error}</p>}{rows.length===0&&!loading&&!error&&<p>No notifications are available.</p>}{filtered.length>0&&<table className="table"><thead><tr><th>Title</th><th>Type</th><th>Severity</th><th>Message</th><th>Created</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id} className={!row.read_at?'notification-unread-row':''}><td>{row.title||'—'}</td><td>{row.notification_type||'—'}</td><td>{row.severity||'—'}</td><td>{row.message||'—'}</td><td>{row.created_at?new Date(row.created_at).toLocaleString():'—'}</td><td><span className="pill">{row.read_at?'Read':'Unread'}</span></td><td><div className="notification-actions">{!row.read_at&&<button onClick={()=>void markRead(row)}>Mark Read</button>}{row.action_url&&<button onClick={()=>openAction(row)}>Open</button>}</div></td></tr>)}</tbody></table>}{rows.length>0&&!filtered.length&&<p>No notifications match the current filters.</p>}</section></main>;
}
