'use client';

import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

type Role='admin'|'coordinator'|'trainer'|'viewer';
type CalendarRequest={id:string;request_number:string|null;agency_name:string|null;contact_person:string|null;preferred_date:string|null;confirmed_date:string|null;preferred_start_time:string|null;confirmed_start_time:string|null;training_format:string|null;status:string|null;class_status:string|null;assigned_trainer_id:string|null;training_location:string|null;total_minutes:number|null;};
type Trainer={id:string;full_name:string|null;email:string|null;role:string|null;};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);

const pad=(n:number)=>String(n).padStart(2,'0');
const iso=(d:Date)=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());
const parse=(s:string)=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
const startOfWeek=(d:Date)=>{const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-x.getDay());return x};
const timeMinutes=(s:string|null)=>{if(!s)return null;const [h,m]=s.split(':').map(Number);return h*60+m};
const fmtTime=(s:string|null)=>{if(!s)return'Time TBD';const [h,m]=s.split(':').map(Number);return new Date(2000,0,1,h,m).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})};
const fmtDuration=(n:number|null)=>{const m=Number(n||0);return m?Math.floor(m/60)+'h '+String(m%60).padStart(2,'0')+'m':'—'};
const startTime=(r:CalendarRequest)=>r.confirmed_start_time||r.preferred_start_time||null;

export default function CalendarPage(){
 const [rows,setRows]=useState<CalendarRequest[]>([]);const [trainers,setTrainers]=useState<Trainer[]>([]);const [role,setRole]=useState<Role|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const [search,setSearch]=useState('');const [trainerFilter,setTrainerFilter]=useState('');const [statusFilter,setStatusFilter]=useState('');const [view,setView]=useState<'month'|'week'|'day'>('month');const [anchor,setAnchor]=useState(new Date());
 const [selected,setSelected]=useState<CalendarRequest|null>(null);const [schedule,setSchedule]=useState({trainer:'',date:'',time:''});const [conflicts,setConflicts]=useState<CalendarRequest[]>([]);

 useEffect(()=>{void initialize()},[]);
 async function initialize(){const {data:auth}=await supabase.auth.getUser();if(!auth.user){setError('Sign in is required.');setLoading(false);return;}const {data:profile,error:profileError}=await supabase.from('profiles').select('role,active').eq('id',auth.user.id).maybeSingle();if(profileError||!profile?.active){setError(profileError?.message||'Your Backtrace account is not active.');setLoading(false);return;}setRole(profile.role as Role);await load();const requestId=new URLSearchParams(window.location.search).get('request');if(requestId){const {data}=await supabase.from('training_requests').select('id,request_number,agency_name,contact_person,preferred_date,confirmed_date,preferred_start_time,confirmed_start_time,training_format,status,class_status,assigned_trainer_id,training_location,total_minutes').eq('id',requestId).maybeSingle();if(data)openRequest(data as CalendarRequest);}}
 async function load(){setLoading(true);setError('');const [requestResult,trainerResult]=await Promise.all([supabase.from('training_requests').select('id,request_number,agency_name,contact_person,preferred_date,confirmed_date,preferred_start_time,confirmed_start_time,training_format,status,class_status,assigned_trainer_id,training_location,total_minutes').is('archived_at',null).order('confirmed_date',{ascending:true,nullsFirst:false}),supabase.from('profiles').select('id,full_name,email,role').eq('active',true).in('role',['trainer','coordinator','admin']).order('full_name')]);if(requestResult.error||trainerResult.error)setError(requestResult.error?.message||trainerResult.error?.message||'Unable to load calendar.');else{setRows((requestResult.data||[]) as CalendarRequest[]);setTrainers((trainerResult.data||[]) as Trainer[]);}setLoading(false);}
 function trainerName(id:string|null){const p=trainers.find(x=>x.id===id);return p?(p.full_name||p.email||'Trainer'):'Unassigned';}
 const filtered=useMemo(()=>rows.filter(r=>{const text=[r.request_number,r.agency_name,r.contact_person,r.training_format,r.training_location,trainerName(r.assigned_trainer_id)].filter(Boolean).join(' ').toLowerCase();return(!search.trim()||text.includes(search.trim().toLowerCase()))&&(!trainerFilter||r.assigned_trainer_id===trainerFilter)&&(!statusFilter||r.status===statusFilter)}),[rows,search,trainerFilter,statusFilter,trainers]);
 const conflictIds=useMemo(()=>{const ids=new Set<string>();const groups=new Map<string,CalendarRequest[]>();for(const r of rows){if(!r.confirmed_date||!r.assigned_trainer_id||String(r.status||'').toLowerCase()==='completed'||timeMinutes(startTime(r))===null||!r.total_minutes)continue;const key=r.assigned_trainer_id+'|'+r.confirmed_date;groups.set(key,[...(groups.get(key)||[]),r]);}for(const list of groups.values()){list.sort((a,b)=>(timeMinutes(startTime(a))||0)-(timeMinutes(startTime(b))||0));for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){const a=list[i],b=list[j],as=timeMinutes(startTime(a))!,bs=timeMinutes(startTime(b))!,ae=as+Number(a.total_minutes||0),be=bs+Number(b.total_minutes||0);if(bs>=ae)break;if(as<be&&ae>bs){ids.add(a.id);ids.add(b.id);}}}return ids;},[rows]);
 const scheduled=filtered.filter(r=>Boolean(r.confirmed_date));
 const today=iso(new Date());const next30=new Date();next30.setDate(next30.getDate()+30);const upcoming30=rows.filter(r=>r.confirmed_date&&r.confirmed_date>=today&&r.confirmed_date<=iso(next30)&&String(r.status||'').toLowerCase()!=='completed').length;
 const unassigned=rows.filter(r=>String(r.status||'').toLowerCase()!=='completed'&&!r.assigned_trainer_id);
 const monthMinutes=rows.filter(r=>r.confirmed_date&&parse(r.confirmed_date).getFullYear()===anchor.getFullYear()&&parse(r.confirmed_date).getMonth()===anchor.getMonth()).reduce((sum,r)=>sum+Number(r.total_minutes||0),0);
 function openRequest(r:CalendarRequest){setSelected(r);setSchedule({trainer:r.assigned_trainer_id||'',date:r.confirmed_date||'',time:(r.confirmed_start_time||r.preferred_start_time||'').slice(0,5)});setConflicts([]);setError('');setMessage('');if(r.confirmed_date)setAnchor(parse(r.confirmed_date));}
 async function saveSchedule(){if(!selected)return;if(!['admin','coordinator'].includes(role||'')){setError('Only Administrators and Coordinators can change schedules.');return;}if(!schedule.trainer||!schedule.date||!schedule.time){setError('Assigned trainer, confirmed date, and start time are required.');return;}setSaving(true);setError('');setMessage('');const {data:clashes,error:conflictError}=await supabase.rpc('training_schedule_conflicts',{p_request_id:selected.id,p_confirmed_date:schedule.date,p_confirmed_start_time:schedule.time,p_duration_minutes:selected.total_minutes||1,p_assigned_trainer_id:schedule.trainer});if(conflictError){setError(conflictError.message);setSaving(false);return;}if(clashes?.length){setConflicts(rows.filter(r=>clashes.some((x:any)=>x.request_id===r.id||x.id===r.id)));setError('Scheduling conflict detected. Resolve the overlap before saving.');setSaving(false);return;}if(!window.confirm('Save this confirmed training schedule?')){setSaving(false);return;}const {error:scheduleError}=await supabase.rpc('set_training_schedule',{p_request_id:selected.id,p_confirmed_date:schedule.date,p_confirmed_start_time:schedule.time,p_assigned_trainer_id:schedule.trainer});if(scheduleError)setError(scheduleError.message);else{setMessage('Training schedule updated.');setSelected(null);await load();}setSaving(false);}
 function navigate(dir:number){const d=new Date(anchor);if(view==='month')d.setMonth(d.getMonth()+dir,1);else if(view==='week')d.setDate(d.getDate()+dir*7);else d.setDate(d.getDate()+dir);setAnchor(d);}
 function periodLabel(){if(view==='month')return anchor.toLocaleDateString([],{month:'long',year:'numeric'});if(view==='week'){const s=startOfWeek(anchor),e=new Date(s);e.setDate(e.getDate()+6);return s.toLocaleDateString([],{month:'short',day:'numeric'})+' – '+e.toLocaleDateString([],{month:'short',day:'numeric',year:'numeric'});}return anchor.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric',year:'numeric'});}
 function eventsFor(date:string){return scheduled.filter(r=>r.confirmed_date===date).sort((a,b)=>String(startTime(a)||'99').localeCompare(String(startTime(b)||'99')));}
 function event(r:CalendarRequest){return <button type="button" key={r.id} className={'calendar-event'+(conflictIds.has(r.id)?' conflict':'')+(String(r.status||'').toLowerCase()==='completed'?' completed':'')} onClick={()=>openRequest(r)}><span>{fmtTime(startTime(r))}</span><strong>{r.agency_name||'Agency'}</strong><small>{r.request_number||'Request'} · {trainerName(r.assigned_trainer_id)}</small></button>;}
 function calendar(){if(view==='month'){const first=new Date(anchor.getFullYear(),anchor.getMonth(),1),start=startOfWeek(first);return <div className="calendar-month-grid">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><div className="calendar-dow" key={x}>{x}</div>)}{Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const key=iso(d),events=eventsFor(key);return <div key={key} className={'calendar-day-cell'+(d.getMonth()!==anchor.getMonth()?' other':'')+(key===today?' today':'')}><div className="calendar-day-number">{d.getDate()}</div>{events.slice(0,5).map(event)}{events.length>5&&<small>+{events.length-5} more</small>}</div>})}</div>;}if(view==='week'){const start=startOfWeek(anchor);return <div className="calendar-week-grid">{Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const key=iso(d);return <section key={key}><header><strong>{d.toLocaleDateString([],{weekday:'short'})}</strong><span>{d.toLocaleDateString([],{month:'short',day:'numeric'})}</span></header>{eventsFor(key).map(event)}</section>})}</div>;}const key=iso(anchor);return <div className="calendar-day-view">{eventsFor(key).length?eventsFor(key).map(event):<p>No scheduled training for this day.</p>}</div>;}
 const statuses=Array.from(new Set(rows.map(r=>r.status).filter((x):x is string=>Boolean(x)))).sort();
 return <main className="shell calendar-page"><header className="legacy-page-header"><div><h1>Training Calendar</h1><p>Shared training schedule, workload, conflicts, and manager scheduling.</p></div><div className="calendar-header-actions"><button onClick={()=>{setAnchor(new Date());setView('day')}}>Today</button><button disabled={loading} onClick={()=>void load()}>{loading?'Refreshing…':'Refresh'}</button></div></header>
 <section className="calendar-metrics"><div><span>Upcoming 30 Days</span><strong>{upcoming30}</strong></div><div><span>Unassigned</span><strong>{unassigned.length}</strong></div><div><span>Conflicts</span><strong>{conflictIds.size}</strong></div><div><span>Monthly Hours</span><strong>{(monthMinutes/60).toFixed(monthMinutes%60?1:0)}</strong></div></section>
 <section className="legacy-panel"><div className="calendar-toolbar"><input placeholder="Search agency, request, contact or trainer" value={search} onChange={e=>setSearch(e.target.value)}/><select value={trainerFilter} onChange={e=>setTrainerFilter(e.target.value)}><option value="">All Trainers</option>{trainers.map(t=><option key={t.id} value={t.id}>{t.full_name||t.email} — {t.role}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All Statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>{setSearch('');setTrainerFilter('');setStatusFilter('')}}>Clear</button></div><div className="calendar-period"><button onClick={()=>navigate(-1)}>‹</button><h2>{periodLabel()}</h2><button onClick={()=>navigate(1)}>›</button><select value={view} onChange={e=>setView(e.target.value as 'month'|'week'|'day')}><option value="month">Month</option><option value="week">Week</option><option value="day">Day</option></select></div>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="upload-success">{message}</p>}{calendar()}</section>
 <section className="calendar-side-grid"><section className="legacy-panel"><div className="panel-heading"><h2>Upcoming Scheduled Training</h2><span>{scheduled.filter(r=>r.confirmed_date&&r.confirmed_date>=today).length}</span></div><div className="simple-list">{scheduled.filter(r=>r.confirmed_date&&r.confirmed_date>=today).slice(0,12).map(r=><button className="calendar-side-item" key={r.id} onClick={()=>openRequest(r)}><strong>{r.agency_name}</strong><span>{r.request_number} · {r.confirmed_date} · {fmtTime(startTime(r))}</span></button>)}</div></section><section className="legacy-panel"><div className="panel-heading"><h2>Unassigned Open Requests</h2><span>{unassigned.length}</span></div><div className="simple-list">{unassigned.slice(0,12).map(r=><button className="calendar-side-item" key={r.id} onClick={()=>openRequest(r)}><strong>{r.agency_name}</strong><span>{r.request_number} · Preferred {r.preferred_date||'date TBD'} · {fmtDuration(r.total_minutes)}</span></button>)}</div></section></section>
 <section className="legacy-panel"><h2>Trainer Workload</h2><div className="table-wrap"><table className="table"><thead><tr><th>Trainer</th><th>Open Requests</th><th>Scheduled</th><th>Hours</th></tr></thead><tbody>{trainers.map(t=>{const assigned=rows.filter(r=>r.assigned_trainer_id===t.id&&String(r.status||'').toLowerCase()!=='completed');return <tr key={t.id}><td>{t.full_name||t.email}</td><td>{assigned.length}</td><td>{assigned.filter(r=>Boolean(r.confirmed_date)).length}</td><td>{(assigned.reduce((sum,r)=>sum+Number(r.total_minutes||0),0)/60).toFixed(1)}</td></tr>})}</tbody></table></div></section>
 {selected&&<div className="upload-modal-backdrop"><section className="upload-modal calendar-event-modal" role="dialog" aria-modal="true"><header><div><h2>{selected.agency_name||'Training Request'}</h2><p>{selected.request_number||'Request'}</p></div><button className="modal-close" onClick={()=>setSelected(null)}>Close</button></header><div className="upload-body"><div className="calendar-detail-grid"><div><span>Agency</span><strong>{selected.agency_name||'—'}</strong></div><div><span>Status</span><strong>{selected.class_status||selected.status||'—'}</strong></div><div><span>Contact</span><strong>{selected.contact_person||'—'}</strong></div><div><span>Format</span><strong>{selected.training_format||'—'}</strong></div><div><span>Location</span><strong>{selected.training_location||'—'}</strong></div><div><span>Duration</span><strong>{fmtDuration(selected.total_minutes)}</strong></div></div><div className="schedule-panel"><h3>Confirmed Schedule</h3><p className="subtitle">{['admin','coordinator'].includes(role||'')?'Schedule changes use the conflict-checked manager workflow.':'Only Administrators and Coordinators can change schedules.'}</p><div className="controls"><label>Assigned Trainer<select disabled={!['admin','coordinator'].includes(role||'')} value={schedule.trainer} onChange={e=>{setSchedule({...schedule,trainer:e.target.value});setConflicts([])}}><option value="">Unassigned</option>{trainers.map(t=><option key={t.id} value={t.id}>{t.full_name||t.email}</option>)}</select></label><label>Confirmed Date<input disabled={!['admin','coordinator'].includes(role||'')} type="date" value={schedule.date} onChange={e=>{setSchedule({...schedule,date:e.target.value});setConflicts([])}}/></label><label>Start Time<input disabled={!['admin','coordinator'].includes(role||'')} type="time" value={schedule.time} onChange={e=>{setSchedule({...schedule,time:e.target.value});setConflicts([])}}/></label></div>{conflicts.length>0&&<div className="calendar-conflict-banner"><strong>Scheduling conflict</strong>{conflicts.map(r=><span key={r.id}>{r.request_number} — {r.agency_name}</span>)}</div>}</div></div><footer><a className="cancel-upload" href={'/requests/edit?request='+encodeURIComponent(selected.id)}>Open Request</a>{['admin','coordinator'].includes(role||'')&&<button disabled={saving} onClick={()=>void saveSchedule()}>{saving?'Saving…':'Save Schedule'}</button>}</footer></section></div>}
 </main>;
}
