'use client';

import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

type CalendarRequest={id:string;request_number:string|null;agency_name:string|null;preferred_date:string|null;confirmed_date:string|null;preferred_start_time:string|null;training_format:string|null;status:string|null;class_status:string|null;assigned_trainer_id:string|null;training_location:string|null};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);

function displayDate(value:string|null){if(!value)return 'Date not scheduled';const date=new Date(value+'T12:00:00');return Number.isNaN(date.getTime())?value:date.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'})}
function dateValue(row:CalendarRequest){return row.confirmed_date||row.preferred_date||''}

export default function CalendarPage(){
 const [rows,setRows]=useState<CalendarRequest[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [search,setSearch]=useState('');const [status,setStatus]=useState('all');
 async function load(){setLoading(true);setError('');const {data:auth}=await supabase.auth.getSession();if(!auth.session){setError('Administrator sign-in is required.');setLoading(false);return}const {data,error}=await supabase.from('training_requests').select('id,request_number,agency_name,preferred_date,confirmed_date,preferred_start_time,training_format,status,class_status,assigned_trainer_id,training_location').is('archived_at',null).order('confirmed_date',{ascending:true,nullsFirst:false});if(error)setError(error.message);else setRows((data||[]) as CalendarRequest[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 const visible=useMemo(()=>rows.filter(row=>{const text=[row.request_number,row.agency_name,row.training_format,row.training_location,row.status,row.class_status].filter(Boolean).join(' ').toLowerCase();const matchesSearch=!search.trim()||text.includes(search.toLowerCase().trim());const rowStatus=String(row.class_status||row.status||'').toLowerCase();const matchesStatus=status==='all'||(status==='scheduled'&&Boolean(row.confirmed_date))||(status==='open'&&!['completed','closed','cancelled'].includes(rowStatus));return matchesSearch&&matchesStatus}),[rows,search,status]);
 return <main className="shell legacy-admin-page"><header className="legacy-page-header"><div><h1>Training Calendar</h1><p>Review scheduled and requested training dates across all active agencies.</p></div><button onClick={()=>void load()} disabled={loading}>Refresh</button></header><section className="legacy-panel"><div className="panel-heading"><div><h2>Calendar</h2><span>{visible.length} training request{visible.length===1?'':'s'}</span></div></div><div className="portal-toolbar"><input aria-label="Search calendar" placeholder="Search agency, request, format or location" value={search} onChange={event=>setSearch(event.target.value)}/><select aria-label="Filter calendar" value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All requests</option><option value="scheduled">Scheduled</option><option value="open">Open requests</option></select><button onClick={()=>{setSearch('');setStatus('all')}}>Clear</button></div>{error&&<p className="error">{error}</p>}{loading&&<p className="empty-attendance">Loading calendar…</p>}{!loading&&!error&&!visible.length&&<p className="empty-attendance">No training requests found.</p>}{visible.length>0&&<div className="calendar-list">{visible.map(row=><article key={row.id}><div className="calendar-date"><strong>{displayDate(dateValue(row))}</strong><small>{row.preferred_start_time||'Time not set'}</small></div><div><strong>{row.request_number||'Training request'}</strong><p>{row.agency_name||'Unnamed agency'} · {row.training_format||'Format not set'}{row.training_location?' · '+row.training_location:''}</p></div><span className="request-status-pill">{row.class_status||row.status||'Received'}</span></article>)}</div>}</section></main>;
}
