'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
const pad=(n:number)=>String(n).padStart(2,'0');
const iso=(d:Date)=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());
const hours=(m:any)=>{const n=Number(m||0);return (n/60).toFixed(n%60?1:0)};
const fmtDate=(s:any)=>s?new Date(String(s)+'T00:00:00').toLocaleDateString():'—';
function rangeFor(preset:string){const now=new Date();let start=new Date(now);if(preset==='year')start=new Date(now.getFullYear(),0,1);else if(preset==='90')start.setDate(now.getDate()-89);else if(preset==='30')start.setDate(now.getDate()-29);else if(preset==='all')start=new Date(2020,0,1);return{start:iso(start),end:iso(now)};}

export default function Reports(){
 const initial=rangeFor('year');
 const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 const [start,setStart]=useState(initial.start);const [end,setEnd]=useState(initial.end);const [preset,setPreset]=useState('year');
 useEffect(()=>{void initialize()},[]);
 async function initialize(){const {data:auth}=await supabase.auth.getUser();if(!auth.user){setError('Sign in is required.');setLoading(false);return;}const {data:profile,error:profileError}=await supabase.from('profiles').select('role,active').eq('id',auth.user.id).maybeSingle();if(profileError||!profile?.active||!['admin','coordinator'].includes(profile.role)){setError(profileError?.message||'Administrator or Coordinator access is required.');setLoading(false);return;}await load(initial.start,initial.end);}
 async function load(from=start,to=end){setLoading(true);setError('');const {data:result,error}=await supabase.rpc('get_training_management_analytics',{p_start_date:from,p_end_date:to});if(error)setError(error.message);else setData(result);setLoading(false);}
 function applyPreset(value:string){setPreset(value);if(value==='custom')return;const next=rangeFor(value);setStart(next.start);setEnd(next.end);void load(next.start,next.end);}
 function applyRange(){setPreset('custom');void load(start,end);}
 function exportCsv(){const rows=data?.requests||[];const header=['Request','Agency','Status','Trainer','Format','Preferred Date','Confirmed Date','Start Time','Hours','Attendees','Created','Completed'];const lines=rows.map((x:any)=>[x.request_number,x.agency_name,x.status,x.trainer,x.training_format,x.preferred_date||'',x.confirmed_date||'',x.confirmed_start_time||'',hours(x.total_minutes),x.estimated_attendees||'',x.created_at||'',x.completed_at||''].map((v:any)=>'"'+String(v??'').replaceAll('"','""')+'"').join(','));const blob=new Blob([[header.join(','),...lines].join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='Backtrace_Training_Report_'+start+'_to_'+end+'.csv';a.click();URL.revokeObjectURL(url);}
 const k=data?.kpis||{};const monthly=data?.monthly||[];const maxMinutes=useMemo(()=>Math.max(1,...monthly.map((x:any)=>Number(x.total_minutes||0))),[monthly]);
 if(loading&&!data)return <main className="shell"><section className="card"><h1>Management Reporting & Analytics</h1><p>Loading management report…</p></section></main>;
 if(error&&!data)return <main className="shell"><section className="card"><h1>Management Reporting & Analytics</h1><p className="error">{error}</p><a href="/">Return to dashboard</a></section></main>;
 return <main className="shell management-reports-page"><header className="legacy-page-header report-header"><div><h1>Management Reporting & Analytics</h1><p>Training demand, completion, workload, agencies, attendance and requested Backtrace tools.</p></div><div className="report-actions"><button onClick={()=>window.print()}>Print Report</button><button disabled={!data?.requests?.length} onClick={exportCsv}>Export CSV</button><button disabled={loading} onClick={()=>void load()}>{loading?'Refreshing…':'Refresh'}</button></div></header>
 <section className="legacy-panel report-controls"><label>Start Date<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End Date<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Preset<select value={preset} onChange={e=>applyPreset(e.target.value)}><option value="year">This Year</option><option value="90">Last 90 Days</option><option value="30">Last 30 Days</option><option value="all">All Time</option><option value="custom">Custom</option></select></label><button disabled={loading||!start||!end} onClick={applyRange}>Apply Date Range</button></section>
 {error&&<p className="error" role="alert">{error}</p>}
 <section className="report-kpis"><article><span>Total Requests</span><strong>{k.total_requests||0}</strong><small>Requests in range</small></article><article><span>Completion Rate</span><strong>{Number(k.completion_rate||0).toFixed(1)}%</strong><small>{k.completed_requests||0} completed · {k.open_requests||0} open</small></article><article><span>Training Hours</span><strong>{hours(k.total_minutes)}</strong><small>Estimated total</small></article><article><span>Attendees</span><strong>{Number(k.total_attendees||0).toLocaleString()}</strong><small>Estimated attendance</small></article><article><span>Avg. Lead Time</span><strong>{Number(k.avg_lead_days||0).toFixed(1)}</strong><small>Days request → confirmed</small></article><article><span>Needs Action</span><strong>{Number(k.unassigned_requests||0)+Number(k.unscheduled_requests||0)}</strong><small>{k.unassigned_requests||0} unassigned · {k.unscheduled_requests||0} unscheduled</small></article></section>
 <section className="report-two-column"><section className="legacy-panel"><div className="panel-heading"><h2>Monthly Training Volume</h2><span>{fmtDate(data?.start_date)} – {fmtDate(data?.end_date)}</span></div><div className="monthly-bars">{monthly.map((x:any)=><div className="monthly-bar" key={x.month_start} title={(x.request_count||0)+' requests · '+hours(x.total_minutes)+' hours'}><strong>{x.request_count||0}</strong><div style={{height:Math.max(3,Math.round(Number(x.total_minutes||0)/maxMinutes*150))}}></div><small>{new Date(x.month_start+'T00:00:00').toLocaleDateString([],{month:'short'})}</small></div>)}</div></section>
 <section className="legacy-panel"><h2>Status Breakdown</h2><div className="report-breakdown">{(data?.status_stats||[]).map((x:any)=><div key={x.status||'Unknown'}><span>{x.status||'Unknown'}</span><strong>{x.count}</strong></div>)}</div><h2 className="report-subhead">Training Format</h2><div className="report-breakdown">{(data?.format_stats||[]).map((x:any)=><div key={x.training_format||'Unknown'}><span>{x.training_format||'Unknown'}</span><strong>{x.count}</strong></div>)}</div></section></section>
 <section className="legacy-panel"><h2>Trainer Workload & Completion</h2><div className="table-wrap"><table className="table"><thead><tr><th>Trainer</th><th>Requests</th><th>Completed</th><th>Rate</th><th>Hours</th><th>Attendees</th><th>Upcoming</th></tr></thead><tbody>{(data?.trainer_stats||[]).map((x:any)=>{const rate=x.requests?Math.round(Number(x.completed||0)*100/Number(x.requests)):0;return <tr key={x.trainer_id}><td><strong>{x.trainer_name||'—'}</strong></td><td>{x.requests}</td><td>{x.completed}</td><td>{rate}%</td><td>{hours(x.total_minutes)}</td><td>{Number(x.attendees||0).toLocaleString()}</td><td>{x.upcoming}</td></tr>})}</tbody></table></div></section>
 <section className="legacy-panel"><h2>Agency Training Activity</h2><div className="table-wrap"><table className="table"><thead><tr><th>Agency</th><th>Requests</th><th>Completed</th><th>Hours</th><th>Attendees</th><th>Last Training</th></tr></thead><tbody>{(data?.agency_stats||[]).map((x:any)=><tr key={(x.agency_id||'')+'-'+x.agency_name}><td><strong>{x.agency_name||'—'}</strong></td><td>{x.requests}</td><td>{x.completed}</td><td>{hours(x.total_minutes)}</td><td>{Number(x.attendees||0).toLocaleString()}</td><td>{fmtDate(x.last_training)}</td></tr>)}</tbody></table></div></section>
 <section className="legacy-panel"><h2>Most Requested Training Tools</h2><div className="report-tools">{(data?.module_stats||[]).slice(0,30).map((x:any)=><div key={x.id}><span><strong>{x.module_name}</strong><small>{x.category} · {x.duration_minutes} min each</small></span><b>{x.selected_count}×</b></div>)}{!(data?.module_stats||[]).length&&<p>No advanced tools selected in this period.</p>}</div></section>
 <section className="legacy-panel"><div className="panel-heading"><h2>Training Request Detail</h2><span>{(data?.requests||[]).length} records</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Request</th><th>Agency</th><th>Status</th><th>Trainer</th><th>Format</th><th>Confirmed</th><th>Hours</th><th>Attendees</th></tr></thead><tbody>{(data?.requests||[]).map((x:any,index:number)=><tr key={(x.request_number||'request')+'-'+index}><td><strong>{x.request_number||'—'}</strong></td><td>{x.agency_name||'—'}</td><td><span className="pill">{x.status||'—'}</span></td><td>{x.trainer||'—'}</td><td>{x.training_format||'—'}</td><td>{fmtDate(x.confirmed_date)}</td><td>{hours(x.total_minutes)}</td><td>{x.estimated_attendees||'—'}</td></tr>)}</tbody></table></div></section>
 </main>;
}
