'use client';

import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

type Request={id:string;request_number:string|null;agency_name:string|null;requested_by:string|null;contact_person:string|null;contact_email:string|null;trainer_contact_name:string|null;trainer_contact_email:string|null;preferred_date:string|null;preferred_start_time:string|null;confirmed_date:string|null;confirmed_start_time:string|null;training_format:string|null;status:string|null;class_status:string|null;total_minutes:number|null;created_at:string|null;submission_source:string|null;assigned_trainer_id:string|null;};type Trainer={id:string;email:string|null;full_name:string|null;};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
const displayDate=(value:string|null)=>value?new Date(value+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'—';
const displayTime=(value:string|null)=>value?value.slice(0,5):'';
const statusText=(row:Request)=>row.status||row.class_status||'Open';

export default function TrainingRequestsPage(){
 const [rows,setRows]=useState<Request[]>([]);const [trainers,setTrainers]=useState<Trainer[]>([]);const [search,setSearch]=useState('');const [status,setStatus]=useState('All statuses');const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 async function load(){setLoading(true);setError('');const {data:session}=await supabase.auth.getSession();if(!session.session){setError('Administrator sign-in is required.');setLoading(false);return;}const [requestResult,trainerResult]=await Promise.all([supabase.from('training_requests').select('id,request_number,agency_name,requested_by,contact_person,contact_email,trainer_contact_name,trainer_contact_email,preferred_date,preferred_start_time,confirmed_date,confirmed_start_time,training_format,status,class_status,total_minutes,created_at,submission_source,assigned_trainer_id').is('archived_at',null).order('created_at',{ascending:false}),supabase.from('profiles').select('id,email,full_name').eq('role','trainer').eq('active',true).order('email')]);if(requestResult.error||trainerResult.error)setError(requestResult.error?.message||trainerResult.error?.message||'Unable to load training requests.');else{setRows(requestResult.data??[]);setTrainers(trainerResult.data??[]);}setLoading(false);}
 useEffect(()=>{void load();},[]);
 const statuses=useMemo(()=>['All statuses',...Array.from(new Set(rows.flatMap(row=>[row.status,row.class_status]).filter((value):value is string=>Boolean(value)))).sort()],[rows]);
 const filtered=useMemo(()=>{const term=search.trim().toLowerCase();return rows.filter(row=>{const current=statusText(row);const haystack=[row.request_number,row.agency_name,row.contact_person,row.requested_by,row.contact_email,row.trainer_contact_name,row.preferred_date,row.training_format,current].filter(Boolean).join(' ').toLowerCase();return(status==='All statuses'||current===status)&&(!term||haystack.includes(term));});},[rows,search,status]);
 const trainerLabel=(id:string|null)=>{if(!id)return 'Unassigned';const trainer=trainers.find(item=>item.id===id);return trainer?.full_name||trainer?.email||'Assigned';};const counts={open:rows.filter(row=>['open','received','pending'].includes(statusText(row).toLowerCase())).length,received:rows.filter(row=>row.submission_source==='public_request'||row.submission_source==='public').length,unassigned:rows.filter(row=>!row.assigned_trainer_id).length,completed:rows.filter(row=>statusText(row).toLowerCase()==='completed').length};
 function downloadCsv(){const header=['Request','Submitted','Agency / Contact','Trainer Contact','Preferred','Confirmed','Type','Status','Trainer','Duration'];const lines=filtered.map(row=>[row.request_number,displayDate(row.created_at?.slice(0,10)||null),row.agency_name,row.contact_person||row.requested_by,row.preferred_date,row.confirmed_date,row.training_format,statusText(row),trainerLabel(row.assigned_trainer_id),row.total_minutes?Math.round(row.total_minutes/60)+' hr':'' ].map(value=>'"'+String(value??'').replaceAll('"','""')+'"').join(','));const blob=new Blob([[header.join(','),...lines].join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='backtrace-training-requests.csv';link.click();URL.revokeObjectURL(url);}
 return <main className="shell legacy-requests-page"><header className="requests-titlebar"><div><h1>Training Requests</h1><p>Create, review, assign and schedule Backtrace training requests.</p></div><div className="requests-header-actions"><a className="secondary-button" href="/request-training">Agency Request Link &amp; QR</a><a className="primary-button" href="/request-training">New Training Request</a></div></header><section className="request-summary-grid"><div><span>OPEN</span><strong>{counts.open}</strong></div><div><span>RECEIVED</span><strong>{counts.received}</strong></div><div><span>UNASSIGNED</span><strong>{counts.unassigned}</strong></div><div><span>COMPLETED</span><strong>{counts.completed}</strong></div></section><section className="requests-table-panel"><div className="request-controls"><input aria-label="Search training requests" placeholder="Search request, agency, contact or trainer contact" value={search} onChange={event=>setSearch(event.target.value)}/><select aria-label="Filter requests by status" value={status} onChange={event=>setStatus(event.target.value)}>{statuses.map(value=><option key={value}>{value}</option>)}</select><button onClick={()=>void load()} disabled={loading}>{loading?'Loading…':'Refresh'}</button></div>{error&&<p className="error" role="alert">{error}</p>}<div className="requests-table-wrap"><table className="requests-table"><thead><tr><th>REQUEST</th><th>SUBMITTED</th><th>AGENCY / CONTACT</th><th>TRAINER CONTACT</th><th>PREFERRED</th><th>CONFIRMED</th><th>TYPE</th><th>STATUS</th><th>TRAINER</th><th>DURATION</th><th></th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td><strong>{row.request_number||'—'}</strong><small>{row.submission_source||'request'}</small></td><td>{displayDate(row.created_at?.slice(0,10)||null)}</td><td><strong>{row.agency_name||'—'}</strong><small>{row.contact_person||row.requested_by||'—'}{(row.contact_email||row.contact_person)&&row.contact_email?' · '+row.contact_email:''}</small></td><td><strong>{row.trainer_contact_name||'—'}</strong><small>{row.trainer_contact_email||'—'}</small></td><td>{displayDate(row.preferred_date)}<small>{displayTime(row.preferred_start_time)}</small></td><td>{displayDate(row.confirmed_date)}<small>{displayTime(row.confirmed_start_time)}</small></td><td>{row.training_format||'—'}</td><td><span className="request-status-pill">{statusText(row)}</span></td><td>{trainerLabel(row.assigned_trainer_id)}</td><td>{row.total_minutes?Math.round(row.total_minutes/60)+' hr':'—'}</td><td><a className="open-request-button" href={'/requests/edit?request='+encodeURIComponent(row.id)}>Open</a></td></tr>)}</tbody></table></div>{!loading&&!error&&!filtered.length&&<p className="empty-requests">No training requests found.</p>}<div className="requests-footer"><span>{filtered.length} request{filtered.length===1?'':'s'}</span><button className="download-requests" disabled={!filtered.length} onClick={downloadCsv}>Download CSV</button></div></section></main>;
}