'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient,Session} from '@supabase/supabase-js';
type Role='admin'|'trainer'|'viewer';type Request={id:string;agency_name:string|null;preferred_date:string|null;status:string|null;class_status:string|null;assigned_trainer_id:string|null;};type Attendee={agency_name:string|null};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);const closed=new Set(['completed','closed','archived','cancelled','finalized']);
export default function Home(){const [session,setSession]=useState<Session|null>(null);const [role,setRole]=useState<Role|null>(null);const [requests,setRequests]=useState<Request[]>([]);const [attendees,setAttendees]=useState<Attendee[]>([]);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false);
useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session?.user)loadProfile(data.session.user.id)});const {data}=supabase.auth.onAuthStateChange((_e,next)=>{setSession(next);if(next?.user)loadProfile(next.user.id);else setRole(null)});return()=>data.subscription.unsubscribe()},[]);
async function loadProfile(id:string){const {data}=await supabase.from('profiles').select('role').eq('id',id).maybeSingle();setRole((data?.role as Role)||null)}
useEffect(()=>{if(session)loadDashboard()},[session]);
async function loadDashboard(){const [a,b]=await Promise.all([supabase.from('training_requests').select('id,agency_name,preferred_date,status,class_status,assigned_trainer_id').is('archived_at',null).order('preferred_date'),supabase.from('training_attendees').select('agency_name')]);if(a.error)setError(a.error.message);else setRequests(a.data??[]);if(!b.error)setAttendees(b.data??[])}
async function signIn(){setLoading(true);setError('');const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);else{setSession(data.session);if(data.user)loadProfile(data.user.id)}setLoading(false)}
const open=useMemo(()=>requests.filter(r=>!closed.has((r.status||r.class_status||'').toLowerCase())),[requests]);const upcoming=useMemo(()=>{const now=new Date(),end=new Date(now);end.setDate(end.getDate()+30);return open.filter(r=>r.preferred_date&&new Date(r.preferred_date)>=now&&new Date(r.preferred_date)<=end)},[open]);const agencies=new Set(attendees.map(a=>a.agency_name).filter(Boolean)).size;
if(!session)return <main className="auth-screen"><section className="auth-card"><div className="eyebrow">BACKTRACE</div><h1>Training Administration</h1><p>Sign in to continue.</p><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button disabled={loading||!email||!password} onClick={signIn}>{loading?'Signing in…':'Sign In'}</button>{error&&<p className="error">{error}</p>}</section></main>;
return <main className="app-shell"><section className="dashboard"><h1>Training Administration Dashboard</h1><p className="lead">Shared operational view of requests, scheduling, agencies and training activity.</p><div className="metrics"><div><label>OPEN REQUESTS</label><strong>{open.length}</strong></div><div><label>RECEIVED</label><strong>{requests.length}</strong></div><div><label>UPCOMING 30 DAYS</label><strong>{upcoming.length}</strong></div><div><label>UNASSIGNED</label><strong>{open.filter(r=>!r.assigned_trainer_id).length}</strong></div><div><label>ACTIVE AGENCIES</label><strong>{agencies}</strong></div></div><div className="dashboard-columns"><section className="dashboard-panel"><h2>Upcoming Training</h2>{upcoming.length?<div className="upcoming-list">{upcoming.map(r=><div className="upcoming-row" key={r.id}><strong>{r.preferred_date}</strong><span>{r.agency_name||'Agency not specified'}</span></div>)}</div>:<p className="empty-state">No upcoming training in the next 30 days.</p>}</section><section className="dashboard-panel"><h2>Quick Actions</h2><div className="quick-grid">{[['Today','Open Today','/today'],['Requests','Open Requests','/requests'],['Attendance','Open Attendance','/classes'],['Attendees','Open Attendees','/attendees'],['Agency History','Open Agency History','/agencies'],['Completion','Open Completion','/completions']].map(([a,b,c])=><a href={c} key={a}><strong>{a}</strong><span>{b}</span></a>)}</div></section></div></section><a className="report-problem" href="/report-problem">Report a Problem</a></main>}