'use client';

import {useEffect,useState} from 'react';
import {createClient,User} from '@supabase/supabase-js';

type Role='admin'|'trainer'|'coordinator'|'viewer';
type Profile={id:string;email:string|null;full_name:string|null;role:Role;active:boolean;created_at:string|null};
type Activity={id:string;action:string;created_at:string;actor_id:string|null;target_user_id:string|null};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);

function generatePassword(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';const bytes=crypto.getRandomValues(new Uint8Array(18));return Array.from(bytes,x=>chars[x%chars.length]).join('')}

export default function UserManagementPage(){
 const [user,setUser]=useState<User|null>(null),[rows,setRows]=useState<Profile[]>([]),[activity,setActivity]=useState<Activity[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[credential,setCredential]=useState<{title:string;message:string;password:string}|null>(null),[fullName,setFullName]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState<Role>('trainer'),[password,setPassword]=useState('');
 useEffect(()=>{setPassword(generatePassword());void load()},[]);
 async function invoke(body:Record<string,unknown>){const {data,error}=await supabase.functions.invoke('manage-training-users',{body});if(error)throw new Error(error.message||'Administration request failed');if(data?.error)throw new Error(data.error);return data}
 async function load(){setLoading(true);setError('');const {data:auth}=await supabase.auth.getUser();if(!auth.user){setError('Administrator sign-in is required.');setLoading(false);return}setUser(auth.user);const {data:me}=await supabase.from('profiles').select('role,active').eq('id',auth.user.id).maybeSingle();if(me?.role!=='admin'||!me.active){setError('Administrator access is required.');setLoading(false);return}const [profiles,logs]=await Promise.all([supabase.from('profiles').select('id,email,full_name,role,active,created_at').order('full_name'),supabase.from('user_management_activity').select('id,action,created_at,actor_id,target_user_id').order('created_at',{ascending:false}).limit(25)]);if(profiles.error)setError(profiles.error.message);else setRows((profiles.data||[]) as Profile[]);if(!logs.error)setActivity((logs.data||[]) as Activity[]);setLoading(false)}
 async function createUser(event:React.FormEvent){event.preventDefault();setBusy('create');setError('');setMessage('');try{const result=await invoke({action:'create',full_name:fullName.trim(),email:email.trim(),role,temporary_password:password});setCredential({title:'User created',message:(result.user?.full_name||fullName)+' ('+(result.user?.email||email)+') can now sign in with this temporary password.',password:result.temporary_password||password});setFullName('');setEmail('');setRole('trainer');setPassword(generatePassword());await load();setMessage('User account created.')}catch(e){setError(e instanceof Error?e.message:'Unable to create user.')}finally{setBusy('')}}
 async function save(profile:Profile){setBusy(profile.id);setError('');try{const name=(document.querySelector('[data-name="'+profile.id+'"]') as HTMLInputElement)?.value.trim()||profile.full_name||'';const selected=(document.querySelector('[data-role="'+profile.id+'"]') as HTMLSelectElement)?.value||profile.role;const active=(document.querySelector('[data-active="'+profile.id+'"]') as HTMLInputElement)?.checked??profile.active;await invoke({action:'update',target_user_id:profile.id,full_name:name,role:selected,active});await load();setMessage('User updated.')}catch(e){setError(e instanceof Error?e.message:'Unable to update user.')}finally{setBusy('')}}
 async function resetPassword(profile:Profile){if(!window.confirm('Generate a new temporary password for '+(profile.full_name||profile.email||'this user')+'? Their current password will stop working immediately.'))return;setBusy('reset-'+profile.id);try{const result=await invoke({action:'reset_password',target_user_id:profile.id});setCredential({title:'Password reset',message:'A new temporary password was created for '+(profile.full_name||profile.email||'this user')+'.',password:result.temporary_password});setMessage('Temporary password generated.')}catch(e){setError(e instanceof Error?e.message:'Unable to reset password.')}finally{setBusy('')}}
 if(loading)return <main className="shell"><section className="card"><h1>User Management</h1><p>Checking administrator permissions…</p></section></main>;
 if(error&&!rows.length)return <main className="shell"><section className="card"><h1>User Management</h1><p className="error">{error}</p><a href="/">Return to dashboard</a></section></main>;
 return <main className="shell user-management-page"><header className="legacy-page-header"><div><h1>User Management</h1><p>Create and administer Backtrace Training accounts.</p></div></header>
 <section className="legacy-panel"><h2>Create User</h2><p className="muted">Create a Trainer, Coordinator, or Administrator. A temporary password is shown after creation.</p><form onSubmit={createUser}><div className="user-create-grid"><label>Full Name<input required value={fullName} onChange={e=>setFullName(e.target.value)}/></label><label>Email Address<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value as Role)}><option value="trainer">Trainer</option><option value="coordinator">Coordinator</option><option value="admin">Administrator</option></select></label><label>Temporary Password<div className="password-row"><input required minLength={10} value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" className="secondary-form-button" onClick={()=>setPassword(generatePassword())}>Generate</button></div></label><button className="public-submit user-create-button" disabled={busy==='create'}>{busy==='create'?'Creating…':'Create User'}</button></div></form></section>
 {credential&&<section className="credential-panel"><strong>{credential.title}</strong><p>{credential.message}</p><code>{credential.password}</code><button className="secondary-form-button" onClick={()=>navigator.clipboard.writeText(credential.password)}>Copy Password</button><small>Provide this password directly to the user.</small></section>}
 <section className="legacy-panel"><div className="panel-heading"><div><h2>Current Users</h2><span>{rows.length} user{rows.length===1?'':'s'}</span></div><button className="secondary-form-button" onClick={()=>void load()} disabled={Boolean(busy)}>Refresh Users</button></div>{error&&<p className="error">{error}</p>}{message&&<p className="upload-success">{message}</p>}<div className="user-table-wrap"><table className="user-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{rows.map(profile=><tr key={profile.id}><td><input data-name={profile.id} defaultValue={profile.full_name||''}/><small>{profile.email||'—'}{profile.id===user?.id&&<b className="self-badge">YOU</b>}</small></td><td><select data-role={profile.id} defaultValue={profile.role} disabled={profile.id===user?.id}><option value="trainer">Trainer</option><option value="coordinator">Coordinator</option><option value="admin">Administrator</option><option value="viewer">Viewer</option></select></td><td><label className="active-toggle"><input data-active={profile.id} type="checkbox" defaultChecked={profile.active} disabled={profile.id===user?.id}/>{profile.active?'Active':'Inactive'}</label></td><td>{profile.created_at?new Date(profile.created_at).toLocaleDateString():'—'}</td><td><button className="secondary-form-button" onClick={()=>void save(profile)} disabled={Boolean(busy)}>Save</button><button className="secondary-form-button" onClick={()=>void resetPassword(profile)} disabled={Boolean(busy)}>Reset Password</button></td></tr>)}</tbody></table></div></section>
 <section className="legacy-panel"><h2>Administration Activity</h2>{activity.length?<div className="activity-list">{activity.map(item=><div key={item.id}><strong>{item.action.replaceAll('_',' ')}</strong><span>{new Date(item.created_at).toLocaleString()}</span></div>)}</div>:<p className="empty-attendance">No administration activity recorded.</p>}</section>
 </main>;
}
