'use client';

import {useEffect,useState} from 'react';
import {createClient,User} from '@supabase/supabase-js';

type Profile={id:string;email:string|null;full_name:string|null;role:'admin'|'trainer'|'viewer';active:boolean;};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
export default function UserManagementPage(){const [user,setUser]=useState<User|null>(null);const [rows,setRows]=useState<Profile[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');
  useEffect(()=>{load();},[]);
  async function load(){setLoading(true);setError('');const {data}=await supabase.auth.getUser();if(!data.user){setError('Administrator sign-in is required.');setLoading(false);return;}setUser(data.user);const {data:me}=await supabase.from('profiles').select('role,active').eq('id',data.user.id).maybeSingle();if(me?.role!=='admin'||!me.active){setError('Administrator access is required.');setLoading(false);return;}const {data:profiles,error}=await supabase.from('profiles').select('id,email,full_name,role,active').order('email');if(error)setError(error.message);else setRows(profiles??[]);setLoading(false);}
  async function changeRole(profile:Profile,role:'trainer'|'viewer'){if(!user||profile.id===user.id||profile.role===role)return;if(!window.confirm('Change '+(profile.email||'this user')+' to '+role+'?'))return;setSaving(profile.id);setError('');setMessage('');const {error:updateError}=await supabase.from('profiles').update({role,updated_at:new Date().toISOString()}).eq('id',profile.id);if(updateError){setError(updateError.message);setSaving('');return;}const {error:logError}=await supabase.from('user_management_activity').insert({actor_id:user.id,target_user_id:profile.id,action:'role_changed',details:{from:profile.role,to:role}});if(logError)setError('Role changed, but the activity log could not be written: '+logError.message);else setMessage('Role updated for '+(profile.email||'user')+'.');await load();setSaving('');}
  if(loading)return <main className="shell"><section className="card"><h1>User Management</h1><p>Checking administrator permissions…</p></section></main>;
  if(error&&!rows.length)return <main className="shell"><section className="card"><h1>User Management</h1><p>{error}</p><a href="/">Return to dashboard</a></section></main>;
  return <main className="shell"><header className="header"><div><div className="brand">User Management</div><div className="subtitle">Administrator-only role assignment</div></div><a href="/">Back to dashboard</a></header><section className="card"><p>Only you remain an Administrator. Other active users may be assigned Trainer or Viewer. Your own Administrator role is locked.</p>{error&&<p>{error}</p>}{message&&<p>{message}</p>}<table className="table"><thead><tr><th>User</th><th>Name</th><th>Status</th><th>Role</th><th>Change role</th></tr></thead><tbody>{rows.map(profile=><tr key={profile.id}><td>{profile.email||'—'}</td><td>{profile.full_name||'—'}</td><td>{profile.active?'Active':'Inactive'}</td><td><span className="pill">{profile.role}</span></td><td>{profile.id===user?.id?<span>Locked</span>:<select disabled={saving===profile.id||!profile.active} value={profile.role==='admin'?'trainer':profile.role} onChange={event=>changeRole(profile,event.target.value as 'trainer'|'viewer')}><option value="trainer">Trainer</option><option value="viewer">Viewer</option></select>}</td></tr>)}</tbody></table></section></main>;
}
