'use client';

import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

type Profile={id:string;full_name:string|null;email:string|null;role:string|null;};
type Activity={event_id:string;occurred_at:string;category:string;action:string;actor_id:string|null;actor_name:string|null;actor_email:string|null;subject:string|null;reference_id:string|null;details:Record<string,any>|null;};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
const pad=(n:number)=>String(n).padStart(2,'0');
const localDate=(d:Date)=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());
const label=(key:string)=>key.split('_').map(x=>x?x[0].toUpperCase()+x.slice(1):'').join(' ');
const value=(v:any)=>v===null||v===undefined||v===''?'Blank':Array.isArray(v)?(v.length?v.join(', '):'None'):typeof v==='boolean'?(v?'Yes':'No'):typeof v==='object'?JSON.stringify(v):String(v);

export default function ActivityLog(){
 const now=new Date(),start30=new Date();start30.setDate(now.getDate()-29);
 const [rows,setRows]=useState<Activity[]>([]);const [profiles,setProfiles]=useState<Profile[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const [search,setSearch]=useState('');const [actor,setActor]=useState('');const [category,setCategory]=useState('');const [from,setFrom]=useState(localDate(start30));const [to,setTo]=useState(localDate(now));const [expanded,setExpanded]=useState<string|null>(null);
 useEffect(()=>{void initialize()},[]);
 async function initialize(){setLoading(true);setError('');const {data:auth}=await supabase.auth.getUser();if(!auth.user){setError('Administrator sign-in is required.');setLoading(false);return;}const {data:me,error:meError}=await supabase.from('profiles').select('role,active').eq('id',auth.user.id).maybeSingle();if(meError||me?.role!=='admin'||!me.active){setError(meError?.message||'Administrator access is required.');setLoading(false);return;}const {data:people,error:profileError}=await supabase.from('profiles').select('id,full_name,email,role').order('full_name');if(profileError){setError(profileError.message);setLoading(false);return;}setProfiles((people||[]) as Profile[]);await load(from,to,'','','');}
 async function load(start=from,end=to,who=actor,cat=category,term=search){setLoading(true);setError('');const pStart=start?new Date(start+'T00:00:00').toISOString():null;let pEnd:string|null=null;if(end){const d=new Date(end+'T00:00:00');d.setDate(d.getDate()+1);pEnd=d.toISOString();}const {data,error}=await supabase.rpc('get_user_activity_history',{p_start:pStart,p_end:pEnd,p_actor:who||null,p_category:cat||null,p_search:term.trim()||null,p_limit:5000});if(error)setError(error.message);else setRows((data||[]) as Activity[]);setLoading(false);}
 function preset(days:number){if(!days){setFrom('');setTo('');void load('','','',category,search);return;}const e=new Date(),s=new Date();s.setDate(e.getDate()-days+1);const sf=localDate(s),et=localDate(e);setFrom(sf);setTo(et);void load(sf,et,actor,category,search);}
 function summary(r:Activity){const d=r.details||{},changes=d.changes;if(r.action==='modules_changed')return 'Selections: '+(d.added||[]).length+' added, '+(d.removed||[]).length+' removed.';if(r.action==='password_reset')return 'Password reset; password value not logged.';if(r.action==='attendee_registered')return 'Attendee registered for training.';if(r.action==='attendee_checked_in')return 'Attendee checked in to training.';if(r.action==='certificate_issued')return 'Training certificate issued.';if(r.action==='attendee_marked_ineligible')return 'Attendee marked ineligible for a certificate.';if(r.action==='attendance_link_generated')return 'Secure training sign-up/check-in link generated.';if(changes){const keys=Object.keys(changes);return 'Changed '+keys.length+' field'+(keys.length===1?'':'s')+': '+keys.slice(0,4).map(label).join(', ')+(keys.length>4?'…':'')+'.';}if(r.action==='created')return 'Training request created.';if(r.action==='user_created')return 'User account created.';return label(r.action)+'.';}
 function renderDetails(r:Activity){const d=r.details||{};let changes=d.changes;if(!changes&&r.action==='user_updated'&&d.from&&d.to){changes={};for(const key of Object.keys(d.to))if(JSON.stringify(d.from[key])!==JSON.stringify(d.to[key]))changes[key]={from:d.from[key],to:d.to[key]};}if(r.action==='modules_changed')return <div className="audit-module-change"><div><strong>Added</strong>{(d.added||[]).length?<ul>{d.added.map((m:any,i:number)=><li key={i}>{m.name||m.id}</li>)}</ul>:<span>None</span>}</div><div><strong>Removed</strong>{(d.removed||[]).length?<ul>{d.removed.map((m:any,i:number)=><li key={i}>{m.name||m.id}</li>)}</ul>:<span>None</span>}</div></div>;if(changes&&Object.keys(changes).length)return <table className="table audit-change-table"><thead><tr><th>Field</th><th>Previous Value</th><th>New Value</th></tr></thead><tbody>{Object.entries(changes).map(([key,v]:[string,any])=><tr key={key}><td><strong>{label(key)}</strong></td><td>{value(v?.before??v?.from)}</td><td>{value(v?.after??v?.to)}</td></tr>)}</tbody></table>;if(d.snapshot)return <table className="table audit-change-table"><thead><tr><th>Field</th><th>Initial Value</th></tr></thead><tbody>{Object.entries(d.snapshot).map(([key,v])=><tr key={key}><td><strong>{label(key)}</strong></td><td>{value(v)}</td></tr>)}</tbody></table>;return <pre className="audit-json">{JSON.stringify(d,null,2)}</pre>;}
 function exportCsv(){const header=['Date/Time','User','Email','Category','Activity','Subject','Summary','Details'];const lines=rows.map(r=>[r.occurred_at,r.actor_name,r.actor_email,r.category,label(r.action),r.subject,summary(r),JSON.stringify(r.details||{})].map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(','));const blob=new Blob([[header.join(','),...lines].join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='Backtrace_User_Activity.csv';a.click();URL.revokeObjectURL(url);}
 const categories=useMemo(()=>Array.from(new Set(rows.map(r=>r.category).filter(Boolean))).sort(),[rows]);const today=new Date().toLocaleDateString();const kpis={events:rows.length,user:rows.filter(r=>r.actor_id).length,requests:rows.filter(r=>r.category==='Requests').length,admin:rows.filter(r=>['User Administration','Agencies','Agency Portal','Email Settings'].includes(r.category)).length,today:rows.filter(r=>new Date(r.occurred_at).toLocaleDateString()===today).length};
 if(loading&&!rows.length)return <main className="shell"><section className="card"><h1>User Activity History</h1><p>Checking administrator access and loading audit history…</p></section></main>;
 if(error&&!rows.length)return <main className="shell"><section className="card"><h1>User Activity History</h1><p className="error">{error}</p><a href="/">Return to dashboard</a></section></main>;
 return <main className="shell audit-history-page"><header className="legacy-page-header"><div><h1>User Activity History</h1><p>Exact audit history of Backtrace Training changes.</p></div><div className="audit-header-actions"><button disabled={!rows.length} onClick={exportCsv}>Export CSV</button><button disabled={loading} onClick={()=>void load()}>{loading?'Refreshing…':'Refresh'}</button></div></header>
 <section className="audit-kpis"><div><span>Events</span><strong>{kpis.events}</strong></div><div><span>User Actions</span><strong>{kpis.user}</strong></div><div><span>Requests</span><strong>{kpis.requests}</strong></div><div><span>Admin / Agency</span><strong>{kpis.admin}</strong></div><div><span>Today</span><strong>{kpis.today}</strong></div></section>
 <section className="legacy-panel"><div className="audit-filters"><input placeholder="Search user, action, agency, request..." value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load()}}/><select value={actor} onChange={e=>setActor(e.target.value)}><option value="">All users / system</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.full_name||p.email} — {p.role}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{['Requests','User Administration','Agencies','Agency Portal','Attendance','Authentication','Email Settings',...categories.filter(c=>!['Requests','User Administration','Agencies','Agency Portal','Attendance','Authentication','Email Settings'].includes(c))].map(c=><option key={c}>{c}</option>)}</select><input aria-label="Start date" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input aria-label="End date" type="date" value={to} onChange={e=>setTo(e.target.value)}/><button onClick={()=>void load()}>Apply</button></div><div className="audit-preset-row"><strong>{rows.length} event{rows.length===1?'':'s'}</strong><div><button onClick={()=>preset(7)}>7 Days</button><button onClick={()=>preset(30)}>30 Days</button><button onClick={()=>preset(90)}>90 Days</button><button onClick={()=>preset(0)}>All</button></div></div>{error&&<p className="error">{error}</p>}{!rows.length&&!loading?<p>No activity matches the filters.</p>:<div className="audit-list"><div className="audit-list-head"><span>Date / Time</span><span>User</span><span>Category</span><span>Activity</span><span>Record / Summary</span><span>Details</span></div>{rows.map(r=><article key={r.event_id} className="audit-row"><div><strong>{new Date(r.occurred_at).toLocaleString()}</strong></div><div><strong>{r.actor_name||'System'}</strong><small>{r.actor_email||'Automated / external'}</small></div><div><span className="pill">{r.category}</span></div><div><strong>{label(r.action)}</strong></div><div><strong>{r.subject||'—'}</strong><small>{summary(r)}</small></div><div><button onClick={()=>setExpanded(expanded===r.event_id?null:r.event_id)}>{expanded===r.event_id?'Hide Details':'View Details'}</button></div>{expanded===r.event_id&&<div className="audit-detail">{renderDetails(r)}</div>}</article>)}</div>}</section>
 </main>;
}
