'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

type Role='admin'|'coordinator'|'trainer'|'viewer';
type Request={id:string;request_number:string|null;agency_name:string|null;confirmed_date:string|null;confirmed_start_time:string|null;assigned_trainer_id:string|null;training_format:string|null;training_location:string|null;teams_meeting_url:string|null;basic_training:boolean|null;train_the_trainer:boolean|null;refresher_course:boolean|null;advanced_training:boolean|null;class_status:string|null;};
type SessionRow={request_id:string;active:boolean;registration_open:boolean;};
type AttendeeRow={request_id:string;checked_in_at:string|null;};
type Trainer={id:string;full_name:string|null;email:string|null;};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
const localDateKey=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
const fmtTime=(t:string|null)=>{if(!t)return'—';const [h,m]=t.split(':').map(Number);return new Date(2000,0,1,h,m).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})};
const trainingType=(r:Request)=>r.train_the_trainer?'Train the Trainer Course':r.refresher_course?'Refresher Course':r.advanced_training?'Advanced Training':r.basic_training?'Basic Backtrace Search Techniques':'Backtrace Training';

export default function Today(){
 const [rows,setRows]=useState<Request[]>([]);const [sessions,setSessions]=useState<SessionRow[]>([]);const [attendees,setAttendees]=useState<AttendeeRow[]>([]);const [trainers,setTrainers]=useState<Trainer[]>([]);const [role,setRole]=useState<Role|null>(null);const [userId,setUserId]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');
 async function load(){setLoading(true);setError('');const {data:auth}=await supabase.auth.getUser();if(!auth.user){setError('Sign in is required.');setLoading(false);return;}setUserId(auth.user.id);const {data:profile,error:profileError}=await supabase.from('profiles').select('role,active').eq('id',auth.user.id).maybeSingle();if(profileError||!profile?.active){setError(profileError?.message||'Your Backtrace account is not active.');setLoading(false);return;}setRole(profile.role as Role);let query=supabase.from('training_requests').select('id,request_number,agency_name,confirmed_date,confirmed_start_time,assigned_trainer_id,training_format,training_location,teams_meeting_url,basic_training,train_the_trainer,refresher_course,advanced_training,class_status').eq('confirmed_date',localDateKey()).is('archived_at',null).order('confirmed_start_time',{ascending:true});if(profile.role==='trainer')query=query.eq('assigned_trainer_id',auth.user.id);const requestResult=await query;if(requestResult.error){setError(requestResult.error.message);setLoading(false);return;}const requests=(requestResult.data??[]) as Request[];setRows(requests);const ids=requests.map(row=>row.id);if(!ids.length){setSessions([]);setAttendees([]);setTrainers([]);setLoading(false);return;}const [directoryResult,trainerResult]=await Promise.all([supabase.rpc('get_training_attendee_directory'),supabase.from('profiles').select('id,full_name,email').eq('active',true)]);if(directoryResult.error||trainerResult.error)setError(directoryResult.error?.message||trainerResult.error?.message||'Unable to load today’s class details.');else{const idSet=new Set(ids);setSessions(((directoryResult.data?.sessions??[]) as SessionRow[]).filter(item=>idSet.has(item.request_id)));setAttendees(((directoryResult.data?.attendance??[]) as AttendeeRow[]).filter(item=>idSet.has(item.request_id)));setTrainers((trainerResult.data??[]) as Trainer[]);}setLoading(false);}
 useEffect(()=>{void load()},[]);
 async function startClass(row:Request){setBusy(row.id);setError('');const {error}=await supabase.rpc('start_training_class',{p_request_id:row.id});if(error)setError(error.message);else await load();setBusy('');}
 async function closeClass(row:Request){if(!window.confirm('Close this class? Registration and check-in will stop and the roster will be preserved.'))return;setBusy(row.id);setError('');const {data,error}=await supabase.rpc('close_training_class',{p_request_id:row.id});if(error)setError(error.message);else if(window.confirm('Class closed. '+(data?.checked_in||0)+' checked in. Open Completion now?'))window.location.assign('/completions?request='+encodeURIComponent(row.id));else await load();setBusy('');}
 return <main className="shell today-page"><section className="card"><div className="header"><div><div className="brand">Today</div><div className="subtitle">{new Date().toLocaleDateString([],{weekday:'long',month:'long',day:'numeric',year:'numeric'})} · {role==='trainer'?'Your assigned classes':'All scheduled classes'}</div></div><button disabled={loading} onClick={()=>void load()}>{loading?'Refreshing…':'Refresh'}</button></div>{error&&<p className="error" role="alert">{error}</p>}{!loading&&!error&&!rows.length&&<p>{role==='trainer'?'You have no assigned classes today.':'There are no training classes scheduled for today.'}</p>}<div className="today-class-list">{rows.map(row=>{const session=sessions.find(item=>item.request_id===row.id);const classAttendees=attendees.filter(item=>item.request_id===row.id);const checked=classAttendees.filter(item=>Boolean(item.checked_in_at)).length;const trainer=trainers.find(item=>item.id===row.assigned_trainer_id);const terminal=['Closed','Completed','Archived'].includes(row.class_status||'');const canStart=!terminal&&row.class_status!=='In Progress'&&Boolean(session?.active);const canClose=['Registration Open','In Progress','Scheduled'].includes(row.class_status||'')&&Boolean(session);return <article className="today-class-card" key={row.id}><div className="today-card-head"><div><h2>{row.agency_name||'Agency'} — {row.request_number||'Training'}</h2><p>{trainingType(row)}</p></div><span className="pill">{row.class_status||'Scheduled'}</span></div><div className="today-facts"><div><span>Start</span><strong>{fmtTime(row.confirmed_start_time)}</strong></div><div><span>Trainer</span><strong>{trainer?.full_name||trainer?.email||'Unassigned'}</strong></div><div><span>Format</span><strong>{row.training_format||'—'}</strong></div><div><span>Location</span><strong>{row.training_location||'—'}</strong></div><div><span>Registered</span><strong>{classAttendees.length}</strong></div><div><span>Checked In</span><strong>{checked}</strong></div></div><div className="today-actions">{canStart&&<button disabled={busy===row.id} onClick={()=>void startClass(row)}>Start Class</button>}{canClose&&<button className="danger-button" disabled={busy===row.id} onClick={()=>void closeClass(row)}>Close Class</button>}<a href="/classes">Attendance</a><a href={'/requests/edit?request='+encodeURIComponent(row.id)}>Request</a>{row.teams_meeting_url&&<a href={row.teams_meeting_url} target="_blank" rel="noreferrer">Join Teams</a>}</div></article>})}</div></section></main>;
}
