'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

type Person={id:string;agency_name:string;badge_id:string|null;full_name:string;email:string;title_position:string|null;first_seen_at:string;last_seen_at:string;};
type Attendance={id:string;person_id:string|null;request_id:string;attendance_status:string|null;certificate_number:string|null;certificate_public_id:string|null;registered_at:string|null;checked_in_at:string|null;};
type Request={id:string;request_number:string|null;confirmed_date:string|null;status:string|null;class_status:string|null;basic_training:boolean|null;train_the_trainer:boolean|null;refresher_course:boolean|null;advanced_training:boolean|null;};
type Completion={request_id:string;actual_training_date:string|null;record_status:string|null;};

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
const fmtDate=(value:string|null|undefined)=>value?new Date(value.length===10?value+'T12:00:00':value).toLocaleDateString():'—';
const trainingType=(r?:Request)=>r?.train_the_trainer?'Train the Trainer':r?.refresher_course?'Refresher':r?.advanced_training?'Advanced':r?.basic_training?'Basic':'Backtrace Training';

export default function Attendees(){
 const [people,setPeople]=useState<Person[]>([]);const [attendance,setAttendance]=useState<Attendance[]>([]);const [requests,setRequests]=useState<Request[]>([]);const [completions,setCompletions]=useState<Completion[]>([]);
 const [search,setSearch]=useState('');const [agency,setAgency]=useState('All agencies');const [selected,setSelected]=useState<Person|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);setError('');const {data:auth}=await supabase.auth.getUser();if(!auth.user){setError('Sign in is required.');setLoading(false);return;}const {data:profile,error:profileError}=await supabase.from('profiles').select('active').eq('id',auth.user.id).maybeSingle();if(profileError||!profile?.active){setError(profileError?.message||'Your Backtrace account is not active.');setLoading(false);return;}const [p,a,r,c]=await Promise.all([supabase.from('training_people').select('id,agency_name,badge_id,full_name,email,title_position,first_seen_at,last_seen_at').order('full_name'),supabase.from('training_attendees').select('id,person_id,request_id,attendance_status,certificate_number,certificate_public_id,registered_at,checked_in_at'),supabase.from('training_requests').select('id,request_number,confirmed_date,status,class_status,basic_training,train_the_trainer,refresher_course,advanced_training'),supabase.from('training_completion_records').select('request_id,actual_training_date,record_status')]);if(p.error||a.error||r.error||c.error)setError(p.error?.message||a.error?.message||r.error?.message||c.error?.message||'Unable to load attendee directory.');else{setPeople((p.data??[]) as Person[]);setAttendance((a.data??[]) as Attendance[]);setRequests((r.data??[]) as Request[]);setCompletions((c.data??[]) as Completion[]);}setLoading(false);}
 const agencies=useMemo(()=>['All agencies',...Array.from(new Set(people.map(p=>p.agency_name).filter(Boolean))).sort()],[people]);
 function history(person:Person){return attendance.filter(a=>a.person_id===person.id);}
 function req(id:string){return requests.find(r=>r.id===id);}
 function completion(id:string){return completions.find(c=>c.request_id===id);}
 function classDate(requestId:string){const r=req(requestId);return completion(requestId)?.actual_training_date||r?.confirmed_date||null;}
 function metrics(person:Person){const h=history(person),requestIds=[...new Set(h.map(a=>a.request_id))],dates=requestIds.map(classDate).filter((v):v is string=>Boolean(v)).sort();return{classes:requestIds.length,certificates:h.filter(a=>Boolean(a.certificate_public_id)).length,last:dates.at(-1)||null};}
 const filtered=useMemo(()=>{const term=search.trim().toLowerCase();return people.filter(p=>(agency==='All agencies'||p.agency_name===agency)&&(!term||[p.full_name,p.email,p.badge_id,p.agency_name,p.title_position].filter(Boolean).join(' ').toLowerCase().includes(term)))},[people,search,agency]);
 function csv(){const head=['Name','Badge / ID','Email','Agency','Title / Position','Classes','Certificates','Last Training'];const lines=filtered.map(p=>{const m=metrics(p);return[p.full_name,p.badge_id,p.email,p.agency_name,p.title_position,m.classes,m.certificates,m.last].map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')});const blob=new Blob([[head.join(','),...lines].join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='backtrace-attendee-directory.csv';a.click();URL.revokeObjectURL(url);}
 const selectedHistory=selected?history(selected).sort((a,b)=>String(classDate(b.request_id)||'').localeCompare(String(classDate(a.request_id)||''))):[];
 const selectedMetrics=selected?metrics(selected):null;
 const certBase=(process.env.NEXT_PUBLIC_SUPABASE_URL||'')+'/functions/v1/public-training-certificate?certificate=';
 return <main className="shell attendee-directory-page"><section className="card"><div className="header"><div><div className="brand">Attendee Directory</div><div className="subtitle">Search people and review class history, attendance, and certificates.</div></div><a href="/">Back to dashboard</a></div><div className="controls"><input aria-label="Search attendees" placeholder="Search name, email, Badge # / ID # or agency" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter attendees by agency" value={agency} onChange={e=>setAgency(e.target.value)}>{agencies.map(v=><option key={v}>{v}</option>)}</select><button onClick={()=>void load()} disabled={loading}>{loading?'Loading…':'Refresh'}</button><button disabled={!filtered.length} onClick={csv}>Download CSV</button></div>{error&&<p className="error">{error}</p>}{!loading&&!error&&!filtered.length&&<p>No attendees match the current search.</p>}{filtered.length>0&&<div className="table-wrap"><table className="table attendee-directory-table"><thead><tr><th>Name</th><th>Badge # / ID #</th><th>Email</th><th>Agency</th><th>Title / Position</th><th>Classes</th><th>Certificates</th><th>Last Training</th></tr></thead><tbody>{filtered.map(person=>{const m=metrics(person);return <tr key={person.id} onClick={()=>setSelected(person)} tabIndex={0} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setSelected(person)}}}><td><strong>{person.full_name}</strong></td><td>{person.badge_id||'—'}</td><td>{person.email}</td><td>{person.agency_name}</td><td>{person.title_position||'—'}</td><td><span className="pill">{m.classes}</span></td><td><span className="pill">{m.certificates}</span></td><td>{fmtDate(m.last)}</td></tr>})}</tbody></table></div>}</section>
 {selected&&selectedMetrics&&<div className="upload-modal-backdrop"><section className="upload-modal attendee-detail-modal" role="dialog" aria-modal="true"><header><div><h2>{selected.full_name}</h2><p>{selected.agency_name}</p></div><button className="modal-close" onClick={()=>setSelected(null)}>Close</button></header><div className="upload-body"><div className="attendee-profile-grid"><div><span>Badge # / ID #</span><strong>{selected.badge_id||'—'}</strong></div><div><span>Email</span><strong>{selected.email}</strong></div><div><span>Title / Position</span><strong>{selected.title_position||'—'}</strong></div><div><span>Agency</span><strong>{selected.agency_name}</strong></div></div><div className="grid attendee-detail-kpis"><div className="metric">Classes<strong>{selectedMetrics.classes}</strong></div><div className="metric">Certificates<strong>{selectedMetrics.certificates}</strong></div><div className="metric">First Seen<strong className="small-metric">{fmtDate(selected.first_seen_at)}</strong></div><div className="metric">Last Training<strong className="small-metric">{fmtDate(selectedMetrics.last)}</strong></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Date</th><th>Request</th><th>Training Type</th><th>Class Status</th><th>Attendance</th><th>Certificate</th></tr></thead><tbody>{selectedHistory.length?selectedHistory.map(item=>{const request=req(item.request_id);return <tr key={item.id}><td>{fmtDate(classDate(item.request_id))}</td><td><strong>{request?.request_number||'—'}</strong></td><td>{trainingType(request)}</td><td>{request?.class_status||request?.status||'—'}</td><td>{item.attendance_status||'—'}</td><td>{item.certificate_public_id?<a className="certificate-link" target="_blank" rel="noreferrer" href={certBase+encodeURIComponent(item.certificate_public_id)}>{item.certificate_number||'Certificate'}</a>:'—'}</td></tr>}):<tr><td colSpan={6}>No class history found.</td></tr>}</tbody></table></div></div><footer><button className="cancel-upload" onClick={()=>setSelected(null)}>Close</button></footer></section></div>}
 </main>;
}
