'use client';

import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

type Category={table:string;label:string};
type RecordItem={table:string;key:Record<string,string|number>;label:string;created?:string};
type Preview={id:string;records:RecordItem[];blockers:RecordItem[];count:number;expires_at:string};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
const identity=(row:RecordItem)=>`${row.table}:${JSON.stringify(row.key)}`;

export default function TestDataCleanupPage(){
 const [authorized,setAuthorized]=useState(false);
 const [categories,setCategories]=useState<Category[]>([]);
 const [table,setTable]=useState('training_requests');
 const [search,setSearch]=useState('');const [offset,setOffset]=useState(0);
 const [rows,setRows]=useState<RecordItem[]>([]);const [selected,setSelected]=useState<RecordItem[]>([]);
 const [preview,setPreview]=useState<Preview|null>(null);const [confirmation,setConfirmation]=useState('');
 const [acknowledged,setAcknowledged]=useState(false);const [busy,setBusy]=useState(false);
 const [error,setError]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{void initialize();},[]);
 async function initialize(){setBusy(true);setError('');setAuthorized(false);try{const {data,error:err}=await supabase.rpc('get_test_cleanup_catalog');if(err)throw err;setAuthorized(true);setCategories(data??[]);await findRows(table,search,0);}catch(err){setError(String((err as {message?:string}).message??'Unable to connect. Retry loading records.'));}finally{setBusy(false);}}
 async function findRows(category=table,query=search,start=offset){setError('');const {data,error:err}=await supabase.rpc('search_test_cleanup_records',{p_table:category,p_search:query,p_offset:start});if(err){setError(err.message);setRows([]);}else{setRows(data??[]);setOffset(start);}}
 function resetPreview(){setPreview(null);setConfirmation('');setAcknowledged(false);setMessage('');}
 function choose(row:RecordItem,checked:boolean){resetPreview();setSelected(previous=>checked?(previous.some(x=>identity(x)===identity(row))?previous:[...previous,row]):previous.filter(x=>identity(x)!==identity(row)));}
 async function buildPreview(){setBusy(true);resetPreview();setError('');try{const {data,error:err}=await supabase.rpc('preview_test_cleanup',{p_roots:selected.map(row=>({table:row.table,key:row.key}))});if(err)throw err;setPreview(data);}catch(err){setError(err instanceof Error?err.message:String((err as {message?:string}).message??err));}finally{setBusy(false);}}
 async function remove(){if(!preview)return;setBusy(true);setError('');try{const {data,error:err}=await supabase.rpc('delete_test_cleanup',{p_plan_id:preview.id,p_confirmation:confirmation});if(err)throw err;setMessage(`Deleted ${data.deleted} test records. Cleanup reference: ${data.cleanup_id}.`);setSelected([]);setPreview(null);setConfirmation('');setAcknowledged(false);await findRows(table,search,0);}catch(err){setError(err instanceof Error?err.message:String((err as {message?:string}).message??err));setPreview(null);setConfirmation('');setAcknowledged(false);}finally{setBusy(false);}}
 function downloadPreview(){if(!preview)return;const csv=[['Category','Record','Key'],...preview.records.map(row=>[categories.find(c=>c.table===row.table)?.label??row.table,row.label,JSON.stringify(row.key)])].map(line=>line.map(value=>'"'+value.replaceAll('"','""')+'"').join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='test-data-cleanup-preview.csv';a.click();URL.revokeObjectURL(url);}
 const phrase=preview?`DELETE ${preview.count} TEST RECORDS`:'';
 const ready=!!preview&&!preview.blockers.length&&acknowledged&&confirmation===phrase&&!busy;
 if(!authorized)return <main className="shell"><section className="card"><h1>{busy?'Checking administrator permissions…':'Administrator access required'}</h1><p>Only active administrators can access test-data cleanup.</p>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} onClick={()=>void initialize()}>Retry access check</button><p><a className="dashboard-return-button" href="/">Return to dashboard</a></p></section></main>;
 return <main className="shell"><section className="card"><h1>Test Data Cleanup</h1><p>Select exact records you know are test data. Preview includes linked classes, attendance, certificates, completions, bug history, notifications, emails, and resource records before deletion.</p><p>Shared records outside your selection block cleanup. Completed test classes and test certificates can be removed through this reviewed workflow.</p><p>Account sign-ins, uploaded files, system settings, numbering counters, release history, manuals, and audit logs are outside this cleanup. Manage accounts in <a href="/user-management">User Management</a> and files in the Resource Library. A restricted audit snapshot of deleted database rows is retained.</p>{error&&<div><p className="error" role="alert">{error}</p>{!categories.length&&<button disabled={busy} onClick={()=>void initialize()}>Retry loading records</button>}</div>}{message&&<p role="status">{message}</p>}
 <div style={{display:'flex',gap:12,flexWrap:'wrap',alignItems:'end'}}><label>Record category<select aria-label="Record category" value={table} disabled={busy||!categories.length} onChange={event=>{setTable(event.target.value);setOffset(0);setRows([]);}}>{categories.map(category=><option key={category.table} value={category.table}>{category.label}</option>)}</select></label><label>Search records<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Name, reference, or test label"/></label><button disabled={busy||!categories.length} onClick={()=>{setBusy(true);void findRows(table,search,0).finally(()=>setBusy(false));}}>Search</button></div>
 <p>Nothing is selected automatically. Up to 100 records can be selected across categories.</p><div style={{overflowX:'auto'}}><table className="cleanup-table"><thead><tr><th>Select</th><th>Record</th><th>Created</th><th>Identifier</th></tr></thead><tbody>{rows.map(row=><tr key={identity(row)}><td><input type="checkbox" aria-label={`Select ${row.label}`} checked={selected.some(x=>identity(x)===identity(row))} disabled={busy||(!selected.some(x=>identity(x)===identity(row))&&selected.length>=100)} onChange={event=>choose(row,event.target.checked)}/></td><td>{row.label}</td><td>{row.created?new Date(row.created).toLocaleDateString():'—'}</td><td style={{fontSize:12}}>{Object.values(row.key).join(' / ')}</td></tr>)}</tbody></table></div>{!rows.length&&!busy&&<p>No matching records. Choose a category and search.</p>}<div style={{display:'flex',gap:8}}><button disabled={busy||offset===0} onClick={()=>{setBusy(true);void findRows(table,search,Math.max(0,offset-50)).finally(()=>setBusy(false));}}>Previous records</button><button disabled={busy||rows.length<50} onClick={()=>{setBusy(true);void findRows(table,search,offset+50).finally(()=>setBusy(false));}}>Next records</button></div>
 <h2>Selected test records ({selected.length})</h2><ul>{selected.map(row=><li key={identity(row)}>{categories.find(c=>c.table===row.table)?.label}: {row.label} <button className="secondary-button" disabled={busy} onClick={()=>choose(row,false)} aria-label={`Remove ${row.label} from selection`}>Remove</button></li>)}</ul><button disabled={busy||!selected.length} onClick={()=>void buildPreview()}>{busy?'Working…':'Preview cleanup'}</button>
 {preview&&<section style={{marginTop:24,borderTop:'1px solid #ccd6e2',paddingTop:20}}><h2>Cleanup preview: {preview.count} records</h2><p>Review every record below. This preview expires in 15 minutes. Changes to the records require a new preview.</p><button className="secondary-button" onClick={downloadPreview}>Download preview CSV</button><div style={{maxHeight:400,overflow:'auto'}}><table className="cleanup-table"><thead><tr><th>Category</th><th>Record</th><th>Identifier</th></tr></thead><tbody>{preview.records.map(row=><tr key={identity(row)}><td>{categories.find(c=>c.table===row.table)?.label??row.table}</td><td>{row.label}</td><td style={{fontSize:12}}>{Object.values(row.key).join(' / ')}</td></tr>)}</tbody></table></div>
 {preview.blockers.length>0?<><h3>Shared records block deletion</h3><p>The following linked records are outside this preview. Only add one if you know it is also test data; otherwise remove the shared parent from your selection.</p><ul>{preview.blockers.map((row,index)=><li key={`${identity(row)}:${index}`}>{categories.find(c=>c.table===row.table)?.label??row.table}: {row.label} {categories.some(c=>c.table===row.table)&&<button className="secondary-button" disabled={busy||selected.length>=100} onClick={()=>choose(row,true)}>Add this test record</button>}</li>)}</ul></>:<><p>Deletion removes these records from the application and invalidates deleted certificate and share links. Sent emails cannot be recalled. Uploaded files require separate file cleanup.</p><label style={{display:'block'}}><input type="checkbox" checked={acknowledged} onChange={event=>setAcknowledged(event.target.checked)}/> I reviewed every record and confirm they are all test data.</label><label style={{display:'block',marginTop:12}}>Type <strong>{phrase}</strong><input aria-label="Deletion confirmation" value={confirmation} onChange={event=>setConfirmation(event.target.value)} autoComplete="off"/></label><button disabled={!ready} onClick={()=>void remove()} style={{background:'#b42318',marginTop:12}}>Delete reviewed test data</button></>}
 </section>}
 <style jsx>{`
.cleanup-table{width:100%;min-width:620px;border-collapse:collapse;margin-top:12px}
.cleanup-table th{padding:10px 12px;text-align:left;background:#f7f9fb;color:#596579;font-size:12px}
.cleanup-table td{padding:10px 12px;border-top:1px solid #e0e7f0;color:#18365f;vertical-align:top}
.cleanup-table input[type=checkbox]{width:18px;height:18px;margin:0}
label select,label input:not([type=checkbox]){display:block;margin-top:6px;min-height:40px;max-width:100%}
`}</style></section></main>;
}

