'use client';
import {FormEvent,useState} from 'react';
import {Agency,Item,Assignment,agencyAddress} from './types';
import styles from './rules.module.css';
type Draft={item_id:string;data_source:string;retention_value:string;retention_unit:string;expected_updated_at:string|null};
type Props={agencyId:string;agencies:Agency[];items:Item[];assignments:Assignment[];canManage:boolean;disabled:boolean;onAgency:(id:string)=>void;onSave:(rows:Draft[])=>Promise<boolean>};
export default function AssignmentWorkspace({agencyId,agencies,items,assignments,canManage,disabled,onAgency,onSave}:Props){
 const [drafts,setDrafts]=useState<Draft[]>([]),[search,setSearch]=useState(''),[view,setView]=useState<'add'|'existing'>(canManage?'add':'existing');
 const agency=agencies.find(a=>a.id===agencyId),saved=assignments.filter(a=>a.agency_id===agencyId);
 const matches=(item:Item)=>`${item.name} ${item.item_type}`.toLowerCase().includes(search.toLowerCase().trim());
 const available=items.filter(i=>!saved.some(a=>a.item_id===i.id)&&matches(i));
 const visibleSaved=saved.filter(a=>{const i=items.find(i=>i.id===a.item_id);return i&&matches(i);});
 function select(item_id:string,existing?:Assignment){setDrafts(rows=>rows.some(r=>r.item_id===item_id)?rows:[...rows,{item_id,data_source:existing?.data_source||'',retention_value:String(existing?.retention_value||90),retention_unit:existing?.retention_unit||'Days',expected_updated_at:existing?.updated_at||null}]);}
 function update(id:string,patch:Partial<Draft>){setDrafts(rows=>rows.map(r=>r.item_id===id?{...r,...patch}:r));}
 async function submit(e:FormEvent){e.preventDefault();if(await onSave(drafts))setDrafts([]);}
 return <form onSubmit={submit} className={styles.assignmentWorkspace}>
  <div className={styles.assignmentBar}><label>Agency<select required disabled={disabled||drafts.length>0} value={agencyId} onChange={e=>{onAgency(e.target.value);setSearch('');}}><option value="">Choose agency</option>{agencies.map(a=><option key={a.id} value={a.id}>{a.agency_name}{a.active?'':' (Inactive)'}</option>)}</select></label><div className={styles.actions}>{canManage&&<><button type="button" disabled={disabled||!drafts.length} onClick={()=>setDrafts([])}>Clear selection</button><button type="submit" className={styles.primary} disabled={disabled||!agency?.active||!drafts.length}>{disabled?'Please wait…':`Save ${drafts.length||''} assignment${drafts.length===1?'':'s'}`}</button></>}</div><p>{(agency?agencyAddress(agency):'')||'Select an agency to review its tools.'}{drafts.length>0?' · Save or clear your selection before switching agencies.':''}</p></div>
  <div className={styles.assignmentGrid}><section className={styles.panel}><h2>Tools</h2><div className={styles.actions}><button type="button" aria-pressed={view==='add'} onClick={()=>setView('add')}>Add tools</button><button type="button" aria-pressed={view==='existing'} onClick={()=>setView('existing')}>Assigned ({saved.length})</button></div><label className={styles.toolSearch}>Search tools<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className={styles.toolList}>
  {view==='add'?available.map(i=><label className={styles.toolOption} key={i.id}><input type="checkbox" checked={drafts.some(r=>r.item_id===i.id)} disabled={disabled||!canManage||!agency?.active||(!drafts.some(r=>r.item_id===i.id)&&drafts.length>=100)} onChange={e=>e.target.checked?select(i.id):setDrafts(rows=>rows.filter(r=>r.item_id!==i.id))}/><span>{i.name}<small>{i.item_type}</small></span></label>):visibleSaved.map(a=>{const item=items.find(i=>i.id===a.item_id);return <div className={styles.savedTool} key={a.id}><div><strong>{item?.name}</strong><small>{a.data_source} · {a.retention_value} {a.retention_unit.toLowerCase()}</small></div>{canManage&&<button type="button" disabled={disabled||!agency?.active||drafts.some(r=>r.item_id===a.item_id)||drafts.length>=100} onClick={()=>select(a.item_id,a)}>Edit</button>}</div>;})}
  {(view==='add'?!available.length:!visibleSaved.length)&&<p>No {view==='add'?'available':'assigned'} tools match.</p>}</div></section>
  <section className={styles.panel}><h2>Assignment details <span className={styles.badge}>{drafts.length} selected</span></h2><p className={styles.description}>Select multiple tools, then enter the data source and retention for each. Save up to 100 assignments together.</p>{drafts.length?<div className={styles.assignmentTable}><table><thead><tr><th>Assigned Tool</th><th>Data source</th><th>Retention</th><th>Unit</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{drafts.map(r=>{const item=items.find(i=>i.id===r.item_id);return <tr key={r.item_id}><td><strong>{item?.name}</strong><small>{r.expected_updated_at?'Update existing':'New assignment'}</small></td><td><input aria-label={`Data source for ${item?.name}`} required maxLength={250} disabled={disabled} value={r.data_source} onChange={e=>update(r.item_id,{data_source:e.target.value})}/></td><td><input aria-label={`Retention period for ${item?.name}`} type="number" required min={1} max={9999} step={1} disabled={disabled} value={r.retention_value} onChange={e=>update(r.item_id,{retention_value:e.target.value})}/></td><td><select aria-label={`Period unit for ${item?.name}`} disabled={disabled} value={r.retention_unit} onChange={e=>update(r.item_id,{retention_unit:e.target.value})}>{['Days','Months','Years'].map(u=><option key={u}>{u}</option>)}</select></td><td><button type="button" aria-label={`Remove ${item?.name} from selection`} disabled={disabled} onClick={()=>setDrafts(rows=>rows.filter(x=>x.item_id!==r.item_id))}>Remove</button></td></tr>;})}</tbody></table></div>:<p>Select tools on the left, or open Assigned to edit existing rules.</p>}</section></div>
 </form>;
}
