begin;
do $test$
declare a uuid;t uuid;g uuid;i uuid;assignment uuid;existing_training uuid;before_count integer;n integer;stamp timestamptz;x jsonb;p jsonb;original jsonb;
begin
 select id into a from public.profiles where active and role='admin' limit 1;
 select id into t from public.profiles where active and role='trainer' limit 1;
 if a is null or t is null then raise exception 'QA needs an active administrator and trainer';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',a::text,true);
 execute 'set local role authenticated';
 insert into public.agencies(agency_name,agency_address,created_by,updated_by) values('Separate Rollback Agency','Training address',a,a) returning id into existing_training;
 select to_jsonb(agencies.*) into original from public.agencies where id=existing_training;
 x:=public.import_business_rules_agencies('[{"agency_name":"Separate Rollback Agency","agency_address":"Business address","agency_city":"QA City","agency_state":"NJ","agency_zip":"00123"},{"agency_name":" SEPARATE  ROLLBACK AGENCY ","agency_address":"Should skip"}]');
 if x<>jsonb_build_object('imported',1,'skipped',1) then raise exception 'Import duplicate result: %',x;end if;
 select id,updated_at into g,stamp from public.business_rules_agencies where agency_name='Separate Rollback Agency';
 if g=existing_training then raise exception 'New business agency reused training identity';end if;
 if (select to_jsonb(agencies.*) from public.agencies where id=existing_training) is distinct from original then raise exception 'Import changed training agency';end if;
 x:=public.import_agencies('[{"agency_name":"separate rollback agency"}]');if (x->>'imported')::int<>0 then raise exception 'Repeat import created duplicate';end if;
 if not exists(select 1 from public.business_rules_agencies where id=g and agency_address='Business address' and agency_zip='00123') then raise exception 'Import overwrote address or ZIP zeros';end if;
 begin perform public.import_business_rules_agencies('[{"agency_name":"Separate Rollback Atomic"},{"agency_name":""}]');raise exception 'Invalid import accepted';exception when raise_exception then if sqlerrm not like 'Invalid agency row.%' then raise;end if;end;
 if exists(select 1 from public.business_rules_agencies where agency_name='Separate Rollback Atomic') then raise exception 'Partial import committed';end if;
 begin insert into public.business_rules_agencies(agency_name) values(' SEPARATE  ROLLBACK AGENCY ');raise exception 'Manual duplicate allowed';exception when unique_violation then null;end;
 insert into public.resource_items(name,item_type,description) values('Separate Rollback Tool','Tool','Description') returning id into i;
 insert into public.agency_item_assignments(agency_id,item_id,data_source,retention_value,retention_unit) values(g,i,'Internal feed',45,'Days') returning id into assignment;
 begin insert into public.agency_item_assignments(agency_id,item_id,data_source,retention_value,retention_unit) values(existing_training,i,'Wrong directory',1,'Days');raise exception 'Assignment linked to training agency';exception when foreign_key_violation then null;end;
 update public.business_rules_agencies set agency_address='Updated internal address' where id=g and updated_at=stamp;
 update public.business_rules_agencies set agency_address='Stale' where id=g and updated_at=stamp;get diagnostics n=row_count;if n<>0 then raise exception 'Stale business agency update succeeded';end if;
 if (select to_jsonb(agencies.*) from public.agencies where id=existing_training) is distinct from original then raise exception 'Business edit changed training';end if;
 update public.agencies set agency_address='Updated training address' where id=existing_training;
 if (select agency_address from public.business_rules_agencies where id=g)<>'Updated internal address' then raise exception 'Training edit changed business registry';end if;
 execute 'reset role';select count(*) into before_count from public.business_rules_agencies;
 perform set_config('request.jwt.claims','{"role":"anon"}',true);perform set_config('request.jwt.claim.sub','',true);execute 'set local role anon';
 p:=jsonb_build_object('agency_name','Separate Rollback Agency','agency_address','Public address','city_state_zip','Public City, NJ, 10001','contact_person','QA Contact','contact_phone','555-0100','contact_email','separate-qa@example.invalid','trainer_contact_name','QA Trainer','trainer_contact_email','trainer-qa@example.invalid','trainer_contact_phone','555-0101','basic_training',true,'training_format','In Person');
 x:=public.submit_public_training_request('',p,'{}');if (x->>'agency_id')::uuid is distinct from existing_training then raise exception 'Training matching used business registry';end if;
 x:=public.submit_public_training_request('',p||'{"agency_name":"Separate Rollback PD","contact_email":"separate-unknown-qa@example.invalid"}','{}');if x->>'agency_id' is not null then raise exception 'Unknown public name guessed business match';end if;
 begin perform id from public.business_rules_agencies;raise exception 'Anonymous registry read permitted';exception when insufficient_privilege then null;end;
 begin perform public.import_business_rules_agencies('[{"agency_name":"Anonymous"}]');raise exception 'Anonymous import permitted';exception when insufficient_privilege then null;end;
 execute 'reset role';
 if (select count(*) from public.business_rules_agencies)<>before_count or (select agency_address from public.business_rules_agencies where id=g)<>'Updated internal address' then raise exception 'Public submission touched internal registry';end if;
 if not exists(select 1 from public.agency_item_assignments where id=assignment and data_source='Internal feed' and retention_value=45) then raise exception 'Public changed rules';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',t,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',t::text,true);execute 'set local role authenticated';
 if not exists(select 1 from public.business_rules_agencies where id=g) then raise exception 'Trainer read denied';end if;
 update public.business_rules_agencies set agency_address='Unauthorized' where id=g;get diagnostics n=row_count;if n<>0 then raise exception 'Trainer edit allowed';end if;
 begin perform public.import_business_rules_agencies('[{"agency_name":"Trainer Import"}]');raise exception 'Trainer import permitted';exception when raise_exception then if sqlerrm not like 'Administrator or Coordinator access%' then raise;end if;end;
 execute 'reset role';update public.profiles set role='coordinator' where id=t;execute 'set local role authenticated';
 x:=public.import_business_rules_agencies('[{"agency_name":"Separate Rollback Coordinator"}]');if (x->>'imported')::int<>1 then raise exception 'Coordinator import denied';end if;
 execute 'reset role';update public.profiles set role='viewer' where id=t;execute 'set local role authenticated';
 if not exists(select 1 from public.business_rules_agencies where id=g) then raise exception 'Viewer read denied';end if;
 update public.business_rules_agencies set agency_address='Viewer edit' where id=g;get diagnostics n=row_count;if n<>0 then raise exception 'Viewer edit allowed';end if;
 execute 'reset role';update public.profiles set active=false where id=t;execute 'set local role authenticated';
 if exists(select 1 from public.business_rules_agencies where id=g) then raise exception 'Inactive registry read allowed';end if;
 execute 'reset role';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',a::text,true);execute 'set local role authenticated';
 p:=public.preview_test_cleanup(jsonb_build_array(jsonb_build_object('table','business_rules_agencies','key',jsonb_build_object('id',g))));
 if (p->>'count')::int<>2 or p->'blockers'<>'[]'::jsonb then raise exception 'Business cleanup crossed into training: %',p;end if;
 perform public.delete_test_cleanup((p->>'id')::uuid,'DELETE 2 TEST RECORDS');
 if exists(select 1 from public.business_rules_agencies where id=g) or exists(select 1 from public.agency_item_assignments where id=assignment) then raise exception 'Business cleanup failed';end if;
 if not exists(select 1 from public.agencies where id=existing_training) or not exists(select 1 from public.resource_items where id=i) then raise exception 'Business cleanup removed training or shared item';end if;
 execute 'reset role';
end $test$;
rollback;
