begin;
do $$
declare a uuid;t uuid;other uuid;r uuid;payload jsonb;result jsonb;checks integer:=0;
begin
select id into a from public.profiles where active and role='admin' limit 1;
select id into t from public.profiles where active and role='trainer' order by id limit 1;
select id into other from public.profiles where active and role='trainer' and id<>t limit 1;
perform set_config('request.jwt.claim.sub',a::text,true);
perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);
payload:=jsonb_build_object('agency_name','QA Trainer Workflow Rollback','agency_address','1 Test Street','city_state_zip','Test City, NJ 07001','contact_person','QA Contact','contact_phone','(201) 555-0123','contact_email','qa@example.invalid','trainer_contact_name','QA Coordinator','trainer_contact_email','qa@example.invalid','trainer_contact_phone','(201) 555-0123','requested_by','QA Test','preferred_date',current_date+7,'training_format','Virtual','estimated_attendees',1,'basic_training',true,'train_the_trainer',false,'refresher_course',false,'advanced_training',false,'time_zone','Eastern','training_resources','[]'::jsonb);
r:=public.save_training_request(null,payload,'{}'::bigint[]);
perform set_config('request.jwt.claim.sub',t::text,true);
begin perform public.set_training_request_teams_link(r,'https://teams.microsoft.com/l/meetup-join/test');raise exception 'FAIL unassigned';exception when others then if sqlerrm not like 'Only managers or%' then raise;end if;end;checks:=checks+1;
perform set_config('request.jwt.claim.sub',a::text,true);
perform public.set_training_schedule(r,current_date+7,'09:00',t);
perform set_config('request.jwt.claim.sub',other::text,true);
begin perform public.respond_to_training_assignment(r,'Accepted',null);raise exception 'FAIL wrong trainer';exception when others then if sqlerrm<>'Only the assigned trainer can respond to this request.' then raise;end if;end;checks:=checks+1;
perform set_config('request.jwt.claim.sub',t::text,true);
begin perform public.set_training_request_teams_link(r,'https://teams.microsoft.com/l/meetup-join/test');raise exception 'FAIL before acceptance';exception when others then if sqlerrm not like 'Only managers or%' then raise;end if;end;checks:=checks+1;
result:=public.respond_to_training_assignment(r,'Accepted',null);
if result->>'trainer_response'<>'Accepted' then raise exception 'FAIL acceptance';end if;checks:=checks+1;
perform public.set_training_request_teams_link(r,'https://teams.microsoft.com/l/meetup-join/test');
if (select teams_meeting_url from public.training_requests where id=r)<>'https://teams.microsoft.com/l/meetup-join/test' then raise exception 'FAIL Teams persistence';end if;checks:=checks+1;
begin perform public.set_training_request_teams_link(r,'https://teams.microsoft.com.evil.example/test');raise exception 'FAIL bad host';exception when others then if sqlerrm<>'Enter a valid Microsoft Teams meeting link.' then raise;end if;end;checks:=checks+1;
perform set_config('request.jwt.claim.sub',a::text,true);
perform public.set_training_schedule(r,current_date+7,'09:00',other);
if (select trainer_response from public.training_requests where id=r)<>'Pending' or (select teams_meeting_url from public.training_requests where id=r) is not null then raise exception 'FAIL reassignment reset';end if;checks:=checks+1;
perform set_config('request.jwt.claim.sub',other::text,true);
begin perform public.respond_to_training_assignment(r,'Declined',null);raise exception 'FAIL reason required';exception when others then if sqlerrm<>'A reason is required when declining.' then raise;end if;end;checks:=checks+1;
perform public.respond_to_training_assignment(r,'Declined','Schedule unavailable');
if (select trainer_decline_reason from public.training_requests where id=r)<>'Schedule unavailable' then raise exception 'FAIL declined reason';end if;checks:=checks+1;
if not exists(select 1 from public.training_notifications where request_id=r and title='Trainer Assignment Declined') then raise exception 'FAIL manager notification';end if;checks:=checks+1;
execute 'set local role authenticated';
begin update public.training_requests set trainer_response='Accepted' where id=r;raise exception 'FAIL raw response update';exception when others then if sqlerrm<>'Use the controlled trainer response workflow.' then raise;end if;end;checks:=checks+1;
execute 'reset role';
set constraints all immediate;
perform set_config('qa.trainer_checks',checks::text,true);
end $$;
select current_setting('qa.trainer_checks')||' trainer workflow checks passed; all writes rolled back' as result;
rollback;