'use client';

import {useEffect,useState} from 'react';
import {createClient,User} from '@supabase/supabase-js';

type Request={id:string;request_number:string|null;agency_name:string|null;requested_by:string|null;preferred_date:string|null;training_format:string|null;status:string|null;class_status:string|null;created_by:string|null;assigned_trainer_id:string|null;};
type Profile={role:string|null;active:boolean|null;};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
const lockedStatuses=new Set(['completed','closed','archived','cancelled','finalized']);

export default function TrainingRequestEditPage(){
  const [requests,setRequests]=useState<Request[]>([]);const [selected,setSelected]=useState<Request|null>(null);const [form,setForm]=useState({agency_name:'',requested_by:'',preferred_date:'',training_format:''});const [user,setUser]=useState<User|null>(null);const [profile,setProfile]=useState<Profile|null>(null);const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [ready,setReady]=useState(false);
  useEffect(()=>{initialize();},[]);
  async function initialize(){const {data}=await supabase.auth.getUser();if(!data.user){setError('Administrator sign-in is required.');setReady(true);return;}setUser(data.user);const {data:row,error:profileError}=await supabase.from('profiles').select('role,active').eq('id',data.user.id).maybeSingle();if(profileError||!row?.active){setError('Your active profile could not be verified.');setReady(true);return;}setProfile(row);await loadRequests();setReady(true);}
  async function loadRequests(){setLoading(true);setError('');const {data,error}=await supabase.from('training_requests').select('id,request_number,agency_name,requested_by,preferred_date,training_format,status,class_status,created_by,assigned_trainer_id').order('created_at',{ascending:false});if(error)setError(error.message);else setRequests(data??[]);setLoading(false);}
  function canEdit(request:Request){const status=(request.class_status||request.status||'').trim().toLowerCase();if(lockedStatuses.has(status))return false;return profile?.role==='admin'||(profile?.role==='trainer'&&(request.created_by===user?.id||request.assigned_trainer_id===user?.id));}
  function choose(request:Request){if(!canEdit(request)){setError('This request is locked or is not assigned to your account.');return;}setSelected(request);setForm({agency_name:request.agency_name||'',requested_by:request.requested_by||'',preferred_date:request.preferred_date||'',training_format:request.training_format||''});setError('');setMessage('');}
  async function save(){if(!selected?.id){setError('This request cannot be edited because it has no record ID.');return;}if(!window.confirm('Save these changes to this training request?'))return;setSaving(true);setError('');setMessage('');const {data}=await supabase.auth.getUser();if(!data.user){setError('Your session has expired.');setSaving(false);return;}const {error}=await supabase.from('training_requests').update({...form,updated_by:data.user.id}).eq('id',selected.id);if(error){setError(error.message);setSaving(false);return;}setMessage('Training request updated.');await loadRequests();setSelected(null);setSaving(false);}
  if(!ready)return <main className="shell"><section className="card"><h1>Edit Training Requests</h1><p>Checking administrator permissions…</p></section></main>;
  if(error&&!requests.length)return <main className="shell"><section className="card"><h1>Edit Training Requests</h1><p>{error}</p><a href="/">Return to dashboard</a></section></main>;
  return <main className="shell"><header className="header"><div><div className="brand">Edit Training Requests</div><div className="subtitle">Role: {profile?.role||'Unassigned'} · completed records remain locked</div></div><a href="/">Back to dashboard</a></header><section className="card"><div className="header"><h2>Training requests</h2><button disabled={loading} onClick={loadRequests}>Refresh</button></div><p className="subtitle">Administrators can edit open requests. Trainers can edit only requests they created or were assigned. Viewers cannot edit.</p>{error&&<p>{error}</p>}{message&&<p>{message}</p>}{loading&&<p>Loading requests…</p>}{requests.length>0&&<table className="table"><thead><tr><th>Request</th><th>Agency</th><th>Requester</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>{requests.map((request,index)=>{const editable=canEdit(request);return <tr key={request.id||index}><td>{request.request_number||'—'}</td><td>{request.agency_name||'—'}</td><td>{request.requested_by||'—'}</td><td>{request.preferred_date||'—'}</td><td><span className="pill">{request.status||request.class_status||'Open'}</span></td><td><button disabled={!editable} onClick={()=>choose(request)}>{editable?'Edit':'Locked'}</button></td></tr>;})}</tbody></table>}{!loading&&!requests.length&&<p>No training requests found.</p>}</section>{selected&&<section className="card" style={{marginTop:20}}><h2>Edit request {selected.request_number}</h2><div className="controls"><label>Agency<input value={form.agency_name} onChange={e=>setForm({...form,agency_name:e.target.value})}/></label><label>Requester<input value={form.requested_by} onChange={e=>setForm({...form,requested_by:e.target.value})}/></label><label>Preferred date<input type="date" value={form.preferred_date.slice(0,10)} onChange={e=>setForm({...form,preferred_date:e.target.value})}/></label><label>Training format<select value={form.training_format} onChange={e=>setForm({...form,training_format:e.target.value})}><option>In Person</option><option>Virtual</option><option>Hybrid</option></select></label></div><button disabled={saving} onClick={save}>{saving?'Saving…':'Save changes'}</button><button disabled={saving} onClick={()=>setSelected(null)}>Cancel</button></section>}</main>;
}
