'use client';

import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

type Version={id:number;version:string|null;release_date:string|null;title:string|null;summary:string|null;is_current:boolean|null;};
type Change={id:number;version_id:number;component:string|null;change_summary:string|null;};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);

export default function VersionHistoryPage(){
  const [auth,setAuth]=useState(false);const [versions,setVersions]=useState<Version[]>([]);const [changes,setChanges]=useState<Change[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
  useEffect(()=>{let active=true;supabase.auth.getSession().then(({data})=>{if(!active)return;if(data.session){setAuth(true);void load(data.session);}else setError('Administrator sign-in is required.');});return()=>{active=false}},[]);
  async function load(existingSession?:{user:{id:string}}){const session=existingSession??(await supabase.auth.getSession()).data.session;if(!session){setError('Administrator sign-in is required.');return;}setAuth(true);setLoading(true);setError('');const [v,c]=await Promise.all([supabase.from('training_app_versions').select('id,version,release_date,title,summary,is_current').order('release_date',{ascending:false}),supabase.from('training_app_version_changes').select('id,version_id,component,change_summary').order('sort_order')]);if(v.error||c.error)setError(v.error?.message||c.error?.message||'Unable to load version history');else{setVersions(v.data??[]);setChanges(c.data??[]);}setLoading(false);}
  function downloadCsv(){const header=['Version','Release date','Title','Summary'];const lines=versions.map(row=>[row.version,row.release_date,row.title,row.summary].map(value=>'"'+String(value??'').replaceAll('"','""')+'"').join(','));const blob=new Blob([[header.join(','),...lines].join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='backtrace-version-history.csv';link.click();URL.revokeObjectURL(url);}
  if(!auth)return <main className="shell"><section className="card"><h1>Version History</h1><p>Loading the current release history…</p><button onClick={()=>void load()}>Load version history</button>{error&&<p role="alert">{error}</p>}<a href="/">Return to dashboard</a></section></main>;
  return <main className="shell version-history-page"><header className="header"><div><div className="brand">Version History</div><div className="subtitle">A clear record of application releases and improvements</div></div><a href="/">Back to dashboard</a></header><section className="card version-history-card"><div className="version-toolbar"><div><h1>Release history</h1><p>Review what changed in each version of Training Administration.</p></div><div className="version-actions"><button disabled={loading} onClick={()=>void load()}>{loading?'Loading…':'Refresh history'}</button><button className="secondary-button" disabled={!versions.length} onClick={downloadCsv}>Download CSV</button></div></div>{error&&<p className="error" role="alert">{error}</p>}{!loading&&!error&&!versions.length&&<p>No release history is available.</p>}<div className="release-list">{versions.map(version=><article className="release-card" key={version.id}><div className="release-marker" aria-hidden="true"/><div className="release-content"><div className="release-heading"><div><span className="release-version">v{version.version||'—'}</span>{version.is_current&&<span className="pill">Current release</span>}</div><time dateTime={version.release_date||undefined}>{version.release_date||'Date unavailable'}</time></div><h2>{version.title||'Untitled release'}</h2><p className="release-summary">{version.summary||'No summary provided.'}</p>{changes.filter(change=>change.version_id===version.id).length>0&&<div className="change-section"><h3>What changed</h3><ul>{changes.filter(change=>change.version_id===version.id).map(change=><li key={change.id}><strong>{change.component||'Change'}</strong><span>{change.change_summary||'No details provided.'}</span></li>)}</ul></div>}</div></article>)}</div></section></main>;
}